// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/micro_mall_order_proto/order_business/order_business.proto

package order_business

import (
	context "context"
	fmt "fmt"
	_ "gitee.com/kelvins-io/common/proto/google/api"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RetCode int32

const (
	RetCode_SUCCESS            RetCode = 0
	RetCode_ERROR              RetCode = 500
	RetCode_USER_NOT_EXIST     RetCode = 50001
	RetCode_USER_EXIST         RetCode = 50002
	RetCode_MERCHANT_NOT_EXIST RetCode = 50003
	RetCode_MERCHANT_EXIST     RetCode = 50004
	RetCode_SHOP_NOT_EXIST     RetCode = 50005
	RetCode_SHOP_EXIST         RetCode = 50006
	RetCode_SKU_NOT_EXIST      RetCode = 50007
	RetCode_SKU_EXIST          RetCode = 50008
)

var RetCode_name = map[int32]string{
	0:     "SUCCESS",
	500:   "ERROR",
	50001: "USER_NOT_EXIST",
	50002: "USER_EXIST",
	50003: "MERCHANT_NOT_EXIST",
	50004: "MERCHANT_EXIST",
	50005: "SHOP_NOT_EXIST",
	50006: "SHOP_EXIST",
	50007: "SKU_NOT_EXIST",
	50008: "SKU_EXIST",
}

var RetCode_value = map[string]int32{
	"SUCCESS":            0,
	"ERROR":              500,
	"USER_NOT_EXIST":     50001,
	"USER_EXIST":         50002,
	"MERCHANT_NOT_EXIST": 50003,
	"MERCHANT_EXIST":     50004,
	"SHOP_NOT_EXIST":     50005,
	"SHOP_EXIST":         50006,
	"SKU_NOT_EXIST":      50007,
	"SKU_EXIST":          50008,
}

func (x RetCode) String() string {
	return proto.EnumName(RetCode_name, int32(x))
}

func (RetCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0ca098091950ff88, []int{0}
}

type OperationType int32

const (
	OperationType_CREATE   OperationType = 0
	OperationType_UPDATE   OperationType = 1
	OperationType_DELETE   OperationType = 2
	OperationType_AUDIT    OperationType = 3
	OperationType_PUT_AWAY OperationType = 4
)

var OperationType_name = map[int32]string{
	0: "CREATE",
	1: "UPDATE",
	2: "DELETE",
	3: "AUDIT",
	4: "PUT_AWAY",
}

var OperationType_value = map[string]int32{
	"CREATE":   0,
	"UPDATE":   1,
	"DELETE":   2,
	"AUDIT":    3,
	"PUT_AWAY": 4,
}

func (x OperationType) String() string {
	return proto.EnumName(OperationType_name, int32(x))
}

func (OperationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0ca098091950ff88, []int{1}
}

type CommonResponse struct {
	Code                 RetCode  `protobuf:"varint,1,opt,name=code,proto3,enum=order_business.RetCode" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonResponse) Reset()         { *m = CommonResponse{} }
func (m *CommonResponse) String() string { return proto.CompactTextString(m) }
func (*CommonResponse) ProtoMessage()    {}
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ca098091950ff88, []int{0}
}

func (m *CommonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonResponse.Unmarshal(m, b)
}
func (m *CommonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonResponse.Marshal(b, m, deterministic)
}
func (m *CommonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonResponse.Merge(m, src)
}
func (m *CommonResponse) XXX_Size() int {
	return xxx_messageInfo_CommonResponse.Size(m)
}
func (m *CommonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommonResponse proto.InternalMessageInfo

func (m *CommonResponse) GetCode() RetCode {
	if m != nil {
		return m.Code
	}
	return RetCode_SUCCESS
}

func (m *CommonResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type CreateOrderRequest struct {
	Uid                  int64           `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	SkuCode              string          `protobuf:"bytes,3,opt,name=sku_code,json=skuCode,proto3" json:"sku_code,omitempty"`
	ShopId               int64           `protobuf:"varint,4,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Price                string          `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	Amount               int64           `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Time                 string          `protobuf:"bytes,7,opt,name=time,proto3" json:"time,omitempty"`
	Name                 string          `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	PayerClientIp        string          `protobuf:"bytes,9,opt,name=payer_client_ip,json=payerClientIp,proto3" json:"payer_client_ip,omitempty"`
	DeviceId             string          `protobuf:"bytes,10,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Description          string          `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	SceneInfo            *OrderSceneInfo `protobuf:"bytes,199,opt,name=scene_info,json=sceneInfo,proto3" json:"scene_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateOrderRequest) Reset()         { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ca098091950ff88, []int{1}
}

func (m *CreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest.Unmarshal(m, b)
}
func (m *CreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest.Merge(m, src)
}
func (m *CreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest.Size(m)
}
func (m *CreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest proto.InternalMessageInfo

func (m *CreateOrderRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CreateOrderRequest) GetSkuCode() string {
	if m != nil {
		return m.SkuCode
	}
	return ""
}

func (m *CreateOrderRequest) GetShopId() int64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *CreateOrderRequest) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *CreateOrderRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *CreateOrderRequest) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *CreateOrderRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateOrderRequest) GetPayerClientIp() string {
	if m != nil {
		return m.PayerClientIp
	}
	return ""
}

func (m *CreateOrderRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *CreateOrderRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateOrderRequest) GetSceneInfo() *OrderSceneInfo {
	if m != nil {
		return m.SceneInfo
	}
	return nil
}

// 支付场景信息
type OrderSceneInfo struct {
	PayerClientIp        string     `protobuf:"bytes,1,opt,name=payer_client_ip,json=payerClientIp,proto3" json:"payer_client_ip,omitempty"`
	DeviceId             string     `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	StoreInfo            *StoreInfo `protobuf:"bytes,999,opt,name=store_info,json=storeInfo,proto3" json:"store_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *OrderSceneInfo) Reset()         { *m = OrderSceneInfo{} }
func (m *OrderSceneInfo) String() string { return proto.CompactTextString(m) }
func (*OrderSceneInfo) ProtoMessage()    {}
func (*OrderSceneInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ca098091950ff88, []int{2}
}

func (m *OrderSceneInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderSceneInfo.Unmarshal(m, b)
}
func (m *OrderSceneInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderSceneInfo.Marshal(b, m, deterministic)
}
func (m *OrderSceneInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderSceneInfo.Merge(m, src)
}
func (m *OrderSceneInfo) XXX_Size() int {
	return xxx_messageInfo_OrderSceneInfo.Size(m)
}
func (m *OrderSceneInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderSceneInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OrderSceneInfo proto.InternalMessageInfo

func (m *OrderSceneInfo) GetPayerClientIp() string {
	if m != nil {
		return m.PayerClientIp
	}
	return ""
}

func (m *OrderSceneInfo) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *OrderSceneInfo) GetStoreInfo() *StoreInfo {
	if m != nil {
		return m.StoreInfo
	}
	return nil
}

// 门店信息
type StoreInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AreaCode             string   `protobuf:"bytes,3,opt,name=area_code,json=areaCode,proto3" json:"area_code,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreInfo) Reset()         { *m = StoreInfo{} }
func (m *StoreInfo) String() string { return proto.CompactTextString(m) }
func (*StoreInfo) ProtoMessage()    {}
func (*StoreInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ca098091950ff88, []int{3}
}

func (m *StoreInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreInfo.Unmarshal(m, b)
}
func (m *StoreInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreInfo.Marshal(b, m, deterministic)
}
func (m *StoreInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreInfo.Merge(m, src)
}
func (m *StoreInfo) XXX_Size() int {
	return xxx_messageInfo_StoreInfo.Size(m)
}
func (m *StoreInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StoreInfo proto.InternalMessageInfo

func (m *StoreInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StoreInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StoreInfo) GetAreaCode() string {
	if m != nil {
		return m.AreaCode
	}
	return ""
}

func (m *StoreInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type CreateOrderResponse struct {
	OrderCode            string   `protobuf:"bytes,1,opt,name=order_code,json=orderCode,proto3" json:"order_code,omitempty"`
	TimeExpire           string   `protobuf:"bytes,2,opt,name=time_expire,json=timeExpire,proto3" json:"time_expire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderResponse) Reset()         { *m = CreateOrderResponse{} }
func (m *CreateOrderResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOrderResponse) ProtoMessage()    {}
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ca098091950ff88, []int{4}
}

func (m *CreateOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderResponse.Unmarshal(m, b)
}
func (m *CreateOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderResponse.Marshal(b, m, deterministic)
}
func (m *CreateOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderResponse.Merge(m, src)
}
func (m *CreateOrderResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOrderResponse.Size(m)
}
func (m *CreateOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderResponse proto.InternalMessageInfo

func (m *CreateOrderResponse) GetOrderCode() string {
	if m != nil {
		return m.OrderCode
	}
	return ""
}

func (m *CreateOrderResponse) GetTimeExpire() string {
	if m != nil {
		return m.TimeExpire
	}
	return ""
}

func init() {
	proto.RegisterEnum("order_business.RetCode", RetCode_name, RetCode_value)
	proto.RegisterEnum("order_business.OperationType", OperationType_name, OperationType_value)
	proto.RegisterType((*CommonResponse)(nil), "order_business.CommonResponse")
	proto.RegisterType((*CreateOrderRequest)(nil), "order_business.CreateOrderRequest")
	proto.RegisterType((*OrderSceneInfo)(nil), "order_business.OrderSceneInfo")
	proto.RegisterType((*StoreInfo)(nil), "order_business.StoreInfo")
	proto.RegisterType((*CreateOrderResponse)(nil), "order_business.CreateOrderResponse")
}

func init() {
	proto.RegisterFile("proto/micro_mall_order_proto/order_business/order_business.proto", fileDescriptor_0ca098091950ff88)
}

var fileDescriptor_0ca098091950ff88 = []byte{
	// 743 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0xcf, 0x6e, 0xdb, 0x46,
	0x10, 0xc6, 0x4b, 0x52, 0xff, 0x38, 0xaa, 0x65, 0x62, 0xed, 0xd6, 0xb4, 0x8d, 0xb6, 0x06, 0x0b,
	0x14, 0x86, 0x8b, 0x9a, 0xa8, 0x7b, 0x6a, 0x0f, 0x46, 0x55, 0x9a, 0x80, 0x85, 0xba, 0x96, 0xb1,
	0xa4, 0xd0, 0xf6, 0x44, 0xd0, 0xe4, 0x5a, 0x59, 0x58, 0xe4, 0x32, 0x5c, 0xca, 0x88, 0xaf, 0x39,
	0xe8, 0x92, 0x4b, 0x80, 0x3c, 0x54, 0x72, 0x4d, 0x9c, 0xc4, 0x79, 0x80, 0x00, 0x79, 0x81, 0x3c,
	0x40, 0xb0, 0xbb, 0x92, 0x20, 0x2b, 0x41, 0x72, 0x9b, 0xf9, 0xed, 0xb7, 0xa3, 0x4f, 0x33, 0xc3,
	0x85, 0x3f, 0x8b, 0x92, 0x55, 0xcc, 0xcd, 0x68, 0x52, 0xb2, 0x28, 0x8b, 0x47, 0xa3, 0x88, 0x95,
	0x29, 0x29, 0x23, 0x85, 0x55, 0x7c, 0x3e, 0xe6, 0x34, 0x27, 0x9c, 0x2f, 0xa5, 0xfb, 0x52, 0x83,
	0x3a, 0x77, 0xe9, 0xd6, 0xe1, 0x90, 0x56, 0x84, 0xec, 0x27, 0x2c, 0x73, 0x2f, 0xc9, 0xe8, 0x8a,
	0xe6, 0xfc, 0x17, 0xca, 0xdc, 0x84, 0x65, 0x19, 0xcb, 0x5d, 0x55, 0x76, 0xc8, 0xd8, 0x70, 0x44,
	0xdc, 0xb8, 0xa0, 0x6e, 0x9c, 0xe7, 0xac, 0x8a, 0x2b, 0xca, 0xf2, 0x69, 0x3d, 0xa7, 0x0f, 0x1d,
	0x4f, 0x8a, 0x31, 0xe1, 0x05, 0xcb, 0x39, 0x41, 0x3f, 0x43, 0x2d, 0x61, 0x29, 0xb1, 0xb5, 0x1d,
	0x6d, 0xb7, 0x73, 0xb0, 0xb1, 0xbf, 0x64, 0x03, 0x93, 0xca, 0x63, 0x29, 0xc1, 0x52, 0x84, 0x2c,
	0x30, 0x32, 0x3e, 0xb4, 0xf5, 0x1d, 0x6d, 0xd7, 0xc4, 0x22, 0x74, 0x6e, 0x75, 0x40, 0x5e, 0x49,
	0xe2, 0x8a, 0xf4, 0xc5, 0x45, 0x4c, 0xee, 0x8f, 0x09, 0xaf, 0x84, 0x70, 0x4c, 0x53, 0x59, 0xd4,
	0xc0, 0x22, 0x44, 0x9b, 0xd0, 0xe2, 0x97, 0xe3, 0x48, 0xfe, 0x96, 0x21, 0xef, 0x37, 0xf9, 0xe5,
	0x58, 0xd4, 0x46, 0x1b, 0xd0, 0xe4, 0xf7, 0x58, 0x11, 0xd1, 0xd4, 0xae, 0xc9, 0x0b, 0x0d, 0x91,
	0xf6, 0x52, 0xb4, 0x0e, 0xf5, 0xa2, 0xa4, 0x09, 0xb1, 0xeb, 0xf2, 0x82, 0x4a, 0xd0, 0xb7, 0xd0,
	0x88, 0x33, 0x36, 0xce, 0x2b, 0xbb, 0xa1, 0xd4, 0x2a, 0x43, 0x08, 0x6a, 0x15, 0xcd, 0x88, 0xdd,
	0x94, 0x62, 0x19, 0x0b, 0x96, 0xc7, 0x19, 0xb1, 0x5b, 0x8a, 0x89, 0x18, 0xfd, 0x04, 0xab, 0x45,
	0x7c, 0x4d, 0xca, 0x28, 0x19, 0x51, 0x92, 0x57, 0x11, 0x2d, 0x6c, 0x53, 0x1e, 0xaf, 0x48, 0xec,
	0x49, 0xda, 0x2b, 0xd0, 0x36, 0x98, 0x29, 0xb9, 0xa2, 0x09, 0x11, 0xc6, 0x40, 0x2a, 0x5a, 0x0a,
	0xf4, 0x52, 0xb4, 0x03, 0xed, 0x94, 0xf0, 0xa4, 0xa4, 0x85, 0x68, 0xaf, 0xdd, 0x96, 0xc7, 0x8b,
	0x08, 0x1d, 0x02, 0xf0, 0x84, 0xe4, 0x24, 0xa2, 0xf9, 0x05, 0xb3, 0x9f, 0x8a, 0x56, 0xb4, 0x0f,
	0xbe, 0x5f, 0xee, 0xaf, 0xec, 0x5a, 0x20, 0x74, 0xbd, 0xfc, 0x82, 0x61, 0x93, 0xcf, 0x42, 0xe7,
	0xb1, 0x06, 0x9d, 0xbb, 0xa7, 0x9f, 0x72, 0xae, 0x7d, 0xd1, 0xb9, 0xbe, 0xe4, 0xfc, 0x77, 0x00,
	0x5e, 0xb1, 0x72, 0xea, 0xeb, 0x5d, 0x53, 0xfa, 0xda, 0x5c, 0xf6, 0x15, 0x08, 0xc9, 0xd4, 0xd2,
	0x2c, 0x74, 0x2e, 0xc0, 0x9c, 0x73, 0xd4, 0x01, 0x7d, 0x3a, 0x61, 0x13, 0xeb, 0x34, 0x9d, 0xb7,
	0x5a, 0x5f, 0x68, 0xf5, 0x36, 0x98, 0x71, 0x49, 0xe2, 0xc5, 0xa9, 0xb7, 0x04, 0x90, 0x63, 0xb7,
	0xa1, 0x19, 0xa7, 0x69, 0x49, 0x38, 0x97, 0x63, 0x37, 0xf1, 0x2c, 0x75, 0x06, 0xb0, 0x76, 0x67,
	0xa7, 0xa6, 0xab, 0xfa, 0x1d, 0x80, 0x72, 0x39, 0x5f, 0x58, 0x13, 0x9b, 0x92, 0xc8, 0x7a, 0x3f,
	0x40, 0x5b, 0xcc, 0x3c, 0x22, 0x0f, 0x0a, 0x5a, 0xce, 0x7c, 0x80, 0x40, 0xbe, 0x24, 0x7b, 0xcf,
	0x34, 0x68, 0x4e, 0xf7, 0x19, 0xb5, 0xa1, 0x19, 0x0c, 0x3c, 0xcf, 0x0f, 0x02, 0xeb, 0x2b, 0x04,
	0x50, 0xf7, 0x31, 0xee, 0x63, 0xeb, 0xbd, 0x81, 0xd6, 0xa1, 0x33, 0x08, 0x7c, 0x1c, 0x9d, 0xf6,
	0xc3, 0xc8, 0xff, 0xaf, 0x17, 0x84, 0xd6, 0xf3, 0x89, 0x81, 0x2c, 0x00, 0x49, 0x15, 0x79, 0x31,
	0x31, 0x90, 0x0d, 0xe8, 0x1f, 0x1f, 0x7b, 0xc7, 0xdd, 0xd3, 0x70, 0x41, 0x7b, 0x33, 0x91, 0x15,
	0xe6, 0x27, 0x8a, 0xbe, 0x54, 0x34, 0x38, 0xee, 0x9f, 0x2d, 0x68, 0x5f, 0xa9, 0xba, 0x92, 0x2a,
	0xf2, 0x7a, 0x62, 0xa0, 0x35, 0x58, 0x09, 0xfe, 0x1e, 0x2c, 0xc8, 0x6e, 0x27, 0x06, 0x5a, 0x05,
	0x53, 0x40, 0x05, 0xde, 0x4c, 0x8c, 0xbd, 0x13, 0x58, 0xe9, 0x17, 0xa4, 0x94, 0xdf, 0x76, 0x78,
	0x5d, 0x10, 0x04, 0xd0, 0xf0, 0xb0, 0xdf, 0x0d, 0x7d, 0xf9, 0x77, 0x1a, 0x83, 0xb3, 0x23, 0x11,
	0x6b, 0x22, 0x3e, 0xf2, 0x4f, 0xfc, 0xd0, 0xb7, 0x74, 0x64, 0x42, 0xbd, 0x3b, 0x38, 0xea, 0x85,
	0x96, 0x81, 0xbe, 0x86, 0xd6, 0xd9, 0x20, 0x8c, 0xba, 0xff, 0x76, 0xff, 0xb7, 0x6a, 0x07, 0x8f,
	0x34, 0x58, 0x97, 0xad, 0xfe, 0x6b, 0x3a, 0xfe, 0x80, 0x94, 0x62, 0x5b, 0x10, 0x87, 0xf6, 0xc2,
	0x20, 0x90, 0xb3, 0xbc, 0x25, 0x1f, 0x7f, 0xf9, 0x5b, 0x3f, 0x7e, 0x56, 0xa3, 0x26, 0xe9, 0x6c,
	0x3f, 0xbc, 0x79, 0xfb, 0x44, 0xff, 0xc6, 0xb1, 0xdc, 0xab, 0x5f, 0xd5, 0xc3, 0xe7, 0x26, 0x52,
	0xf6, 0x87, 0xb6, 0x77, 0xde, 0x90, 0x4f, 0xd5, 0x6f, 0x1f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa5,
	0xe0, 0x3a, 0x0e, 0x3e, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderBusinessServiceClient is the client API for OrderBusinessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderBusinessServiceClient interface {
	// 创建订单
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
}

type orderBusinessServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrderBusinessServiceClient(cc *grpc.ClientConn) OrderBusinessServiceClient {
	return &orderBusinessServiceClient{cc}
}

func (c *orderBusinessServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, "/order_business.OrderBusinessService/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderBusinessServiceServer is the server API for OrderBusinessService service.
type OrderBusinessServiceServer interface {
	// 创建订单
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
}

// UnimplementedOrderBusinessServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrderBusinessServiceServer struct {
}

func (*UnimplementedOrderBusinessServiceServer) CreateOrder(ctx context.Context, req *CreateOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}

func RegisterOrderBusinessServiceServer(s *grpc.Server, srv OrderBusinessServiceServer) {
	s.RegisterService(&_OrderBusinessService_serviceDesc, srv)
}

func _OrderBusinessService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderBusinessServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order_business.OrderBusinessService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderBusinessServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderBusinessService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "order_business.OrderBusinessService",
	HandlerType: (*OrderBusinessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrderBusinessService_CreateOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/micro_mall_order_proto/order_business/order_business.proto",
}
