// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.14.0
// source: proto/micro_mall_search_proto/search_business/search.proto

package search_business

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RetCode int32

const (
	RetCode_SUCCESS            RetCode = 0
	RetCode_ERROR              RetCode = 500
	RetCode_USER_NOT_EXIST     RetCode = 50001
	RetCode_USER_EXIST         RetCode = 50002
	RetCode_MERCHANT_NOT_EXIST RetCode = 50003
	RetCode_MERCHANT_EXIST     RetCode = 50004
	RetCode_SHOP_NOT_EXIST     RetCode = 50005
	RetCode_SHOP_EXIST         RetCode = 50006
	RetCode_SKU_NOT_EXIST      RetCode = 50007
	RetCode_SKU_EXIST          RetCode = 50008
)

// Enum value maps for RetCode.
var (
	RetCode_name = map[int32]string{
		0:     "SUCCESS",
		500:   "ERROR",
		50001: "USER_NOT_EXIST",
		50002: "USER_EXIST",
		50003: "MERCHANT_NOT_EXIST",
		50004: "MERCHANT_EXIST",
		50005: "SHOP_NOT_EXIST",
		50006: "SHOP_EXIST",
		50007: "SKU_NOT_EXIST",
		50008: "SKU_EXIST",
	}
	RetCode_value = map[string]int32{
		"SUCCESS":            0,
		"ERROR":              500,
		"USER_NOT_EXIST":     50001,
		"USER_EXIST":         50002,
		"MERCHANT_NOT_EXIST": 50003,
		"MERCHANT_EXIST":     50004,
		"SHOP_NOT_EXIST":     50005,
		"SHOP_EXIST":         50006,
		"SKU_NOT_EXIST":      50007,
		"SKU_EXIST":          50008,
	}
)

func (x RetCode) Enum() *RetCode {
	p := new(RetCode)
	*p = x
	return p
}

func (x RetCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RetCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_micro_mall_search_proto_search_business_search_proto_enumTypes[0].Descriptor()
}

func (RetCode) Type() protoreflect.EnumType {
	return &file_proto_micro_mall_search_proto_search_business_search_proto_enumTypes[0]
}

func (x RetCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RetCode.Descriptor instead.
func (RetCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_micro_mall_search_proto_search_business_search_proto_rawDescGZIP(), []int{0}
}

type OperationType int32

const (
	OperationType_CREATE   OperationType = 0
	OperationType_UPDATE   OperationType = 1
	OperationType_DELETE   OperationType = 2
	OperationType_AUDIT    OperationType = 3
	OperationType_PUT_AWAY OperationType = 4
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "CREATE",
		1: "UPDATE",
		2: "DELETE",
		3: "AUDIT",
		4: "PUT_AWAY",
	}
	OperationType_value = map[string]int32{
		"CREATE":   0,
		"UPDATE":   1,
		"DELETE":   2,
		"AUDIT":    3,
		"PUT_AWAY": 4,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_micro_mall_search_proto_search_business_search_proto_enumTypes[1].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_proto_micro_mall_search_proto_search_business_search_proto_enumTypes[1]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_proto_micro_mall_search_proto_search_business_search_proto_rawDescGZIP(), []int{1}
}

type ShopSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopKey string `protobuf:"bytes,1,opt,name=shop_key,json=shopKey,proto3" json:"shop_key,omitempty"`
}

func (x *ShopSearchRequest) Reset() {
	*x = ShopSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopSearchRequest) ProtoMessage() {}

func (x *ShopSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopSearchRequest.ProtoReflect.Descriptor instead.
func (*ShopSearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_search_proto_search_business_search_proto_rawDescGZIP(), []int{0}
}

func (x *ShopSearchRequest) GetShopKey() string {
	if x != nil {
		return x.ShopKey
	}
	return ""
}

type ShopSearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common *CommonResponse    `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	List   []*ShopSearchEntry `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ShopSearchResponse) Reset() {
	*x = ShopSearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopSearchResponse) ProtoMessage() {}

func (x *ShopSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopSearchResponse.ProtoReflect.Descriptor instead.
func (*ShopSearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_search_proto_search_business_search_proto_rawDescGZIP(), []int{1}
}

func (x *ShopSearchResponse) GetCommon() *CommonResponse {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *ShopSearchResponse) GetList() []*ShopSearchEntry {
	if x != nil {
		return x.List
	}
	return nil
}

type ShopSearchEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopId   string  `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	ShopName string  `protobuf:"bytes,2,opt,name=shop_name,json=shopName,proto3" json:"shop_name,omitempty"`
	Score    float64 `protobuf:"fixed64,399,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *ShopSearchEntry) Reset() {
	*x = ShopSearchEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopSearchEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopSearchEntry) ProtoMessage() {}

func (x *ShopSearchEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopSearchEntry.ProtoReflect.Descriptor instead.
func (*ShopSearchEntry) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_search_proto_search_business_search_proto_rawDescGZIP(), []int{2}
}

func (x *ShopSearchEntry) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *ShopSearchEntry) GetShopName() string {
	if x != nil {
		return x.ShopName
	}
	return ""
}

func (x *ShopSearchEntry) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type SkuInventorySearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkuKey string `protobuf:"bytes,1,opt,name=sku_key,json=skuKey,proto3" json:"sku_key,omitempty"`
}

func (x *SkuInventorySearchRequest) Reset() {
	*x = SkuInventorySearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkuInventorySearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkuInventorySearchRequest) ProtoMessage() {}

func (x *SkuInventorySearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkuInventorySearchRequest.ProtoReflect.Descriptor instead.
func (*SkuInventorySearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_search_proto_search_business_search_proto_rawDescGZIP(), []int{3}
}

func (x *SkuInventorySearchRequest) GetSkuKey() string {
	if x != nil {
		return x.SkuKey
	}
	return ""
}

type SkuInventoryEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopId  string  `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	SkuCode string  `protobuf:"bytes,2,opt,name=sku_code,json=skuCode,proto3" json:"sku_code,omitempty"`
	SkuName string  `protobuf:"bytes,3,opt,name=sku_name,json=skuName,proto3" json:"sku_name,omitempty"`
	Score   float64 `protobuf:"fixed64,399,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *SkuInventoryEntry) Reset() {
	*x = SkuInventoryEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkuInventoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkuInventoryEntry) ProtoMessage() {}

func (x *SkuInventoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkuInventoryEntry.ProtoReflect.Descriptor instead.
func (*SkuInventoryEntry) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_search_proto_search_business_search_proto_rawDescGZIP(), []int{4}
}

func (x *SkuInventoryEntry) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *SkuInventoryEntry) GetSkuCode() string {
	if x != nil {
		return x.SkuCode
	}
	return ""
}

func (x *SkuInventoryEntry) GetSkuName() string {
	if x != nil {
		return x.SkuName
	}
	return ""
}

func (x *SkuInventoryEntry) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type SkuInventorySearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common *CommonResponse      `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	List   []*SkuInventoryEntry `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *SkuInventorySearchResponse) Reset() {
	*x = SkuInventorySearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkuInventorySearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkuInventorySearchResponse) ProtoMessage() {}

func (x *SkuInventorySearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkuInventorySearchResponse.ProtoReflect.Descriptor instead.
func (*SkuInventorySearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_search_proto_search_business_search_proto_rawDescGZIP(), []int{5}
}

func (x *SkuInventorySearchResponse) GetCommon() *CommonResponse {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *SkuInventorySearchResponse) GetList() []*SkuInventoryEntry {
	if x != nil {
		return x.List
	}
	return nil
}

type MerchantInfoSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *MerchantInfoSearchRequest) Reset() {
	*x = MerchantInfoSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MerchantInfoSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantInfoSearchRequest) ProtoMessage() {}

func (x *MerchantInfoSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantInfoSearchRequest.ProtoReflect.Descriptor instead.
func (*MerchantInfoSearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_search_proto_search_business_search_proto_rawDescGZIP(), []int{6}
}

func (x *MerchantInfoSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type MerchantInfoSearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common *CommonResponse      `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	List   []*MerchantInfoEntry `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *MerchantInfoSearchResponse) Reset() {
	*x = MerchantInfoSearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MerchantInfoSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantInfoSearchResponse) ProtoMessage() {}

func (x *MerchantInfoSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantInfoSearchResponse.ProtoReflect.Descriptor instead.
func (*MerchantInfoSearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_search_proto_search_business_search_proto_rawDescGZIP(), []int{7}
}

func (x *MerchantInfoSearchResponse) GetCommon() *CommonResponse {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *MerchantInfoSearchResponse) GetList() []*MerchantInfoEntry {
	if x != nil {
		return x.List
	}
	return nil
}

type TradeOrderSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *TradeOrderSearchRequest) Reset() {
	*x = TradeOrderSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TradeOrderSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeOrderSearchRequest) ProtoMessage() {}

func (x *TradeOrderSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeOrderSearchRequest.ProtoReflect.Descriptor instead.
func (*TradeOrderSearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_search_proto_search_business_search_proto_rawDescGZIP(), []int{8}
}

func (x *TradeOrderSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type TradeOrderSearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common *CommonResponse   `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	List   []*TradeOrderInfo `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *TradeOrderSearchResponse) Reset() {
	*x = TradeOrderSearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TradeOrderSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeOrderSearchResponse) ProtoMessage() {}

func (x *TradeOrderSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeOrderSearchResponse.ProtoReflect.Descriptor instead.
func (*TradeOrderSearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_search_proto_search_business_search_proto_rawDescGZIP(), []int{9}
}

func (x *TradeOrderSearchResponse) GetCommon() *CommonResponse {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *TradeOrderSearchResponse) GetList() []*TradeOrderInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type TradeOrderInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderCode string  `protobuf:"bytes,1,opt,name=order_code,json=orderCode,proto3" json:"order_code,omitempty"`
	Score     float64 `protobuf:"fixed64,999,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *TradeOrderInfo) Reset() {
	*x = TradeOrderInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TradeOrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeOrderInfo) ProtoMessage() {}

func (x *TradeOrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeOrderInfo.ProtoReflect.Descriptor instead.
func (*TradeOrderInfo) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_search_proto_search_business_search_proto_rawDescGZIP(), []int{10}
}

func (x *TradeOrderInfo) GetOrderCode() string {
	if x != nil {
		return x.OrderCode
	}
	return ""
}

func (x *TradeOrderInfo) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type MerchantInfoEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid          int64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	UserName     string  `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	MerchantCode string  `protobuf:"bytes,3,opt,name=merchant_code,json=merchantCode,proto3" json:"merchant_code,omitempty"`
	Score        float64 `protobuf:"fixed64,999,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *MerchantInfoEntry) Reset() {
	*x = MerchantInfoEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MerchantInfoEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantInfoEntry) ProtoMessage() {}

func (x *MerchantInfoEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantInfoEntry.ProtoReflect.Descriptor instead.
func (*MerchantInfoEntry) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_search_proto_search_business_search_proto_rawDescGZIP(), []int{11}
}

func (x *MerchantInfoEntry) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *MerchantInfoEntry) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *MerchantInfoEntry) GetMerchantCode() string {
	if x != nil {
		return x.MerchantCode
	}
	return ""
}

func (x *MerchantInfoEntry) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type UserSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *UserSearchRequest) Reset() {
	*x = UserSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSearchRequest) ProtoMessage() {}

func (x *UserSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSearchRequest.ProtoReflect.Descriptor instead.
func (*UserSearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_search_proto_search_business_search_proto_rawDescGZIP(), []int{12}
}

func (x *UserSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type UserSearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common *CommonResponse  `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	List   []*UserInfoEntry `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *UserSearchResponse) Reset() {
	*x = UserSearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSearchResponse) ProtoMessage() {}

func (x *UserSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSearchResponse.ProtoReflect.Descriptor instead.
func (*UserSearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_search_proto_search_business_search_proto_rawDescGZIP(), []int{13}
}

func (x *UserSearchResponse) GetCommon() *CommonResponse {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *UserSearchResponse) GetList() []*UserInfoEntry {
	if x != nil {
		return x.List
	}
	return nil
}

type UserInfoEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone string  `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Score float64 `protobuf:"fixed64,999,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *UserInfoEntry) Reset() {
	*x = UserInfoEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfoEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoEntry) ProtoMessage() {}

func (x *UserInfoEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoEntry.ProtoReflect.Descriptor instead.
func (*UserInfoEntry) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_search_proto_search_business_search_proto_rawDescGZIP(), []int{14}
}

func (x *UserInfoEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfoEntry) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserInfoEntry) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type CommonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code RetCode `protobuf:"varint,1,opt,name=code,proto3,enum=search_business.RetCode" json:"code,omitempty"`
	Msg  string  `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_proto_micro_mall_search_proto_search_business_search_proto_rawDescGZIP(), []int{15}
}

func (x *CommonResponse) GetCode() RetCode {
	if x != nil {
		return x.Code
	}
	return RetCode_SUCCESS
}

func (x *CommonResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_proto_micro_mall_search_proto_search_business_search_proto protoreflect.FileDescriptor

var file_proto_micro_mall_search_proto_search_business_search_proto_rawDesc = []byte{
	0x0a, 0x3a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x5f, 0x6d, 0x61,
	0x6c, 0x6c, 0x5f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2f,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x1a, 0x3e, 0x67,
	0x69, 0x74, 0x65, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x65, 0x6c, 0x76, 0x69, 0x6e, 0x73,
	0x2d, 0x69, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a,
	0x11, 0x53, 0x68, 0x6f, 0x70, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x68, 0x6f, 0x70, 0x4b, 0x65, 0x79, 0x22, 0x83, 0x01,
	0x0a, 0x12, 0x53, 0x68, 0x6f, 0x70, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x62, 0x75,
	0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x34, 0x0a,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x53, 0x68,
	0x6f, 0x70, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x22, 0x5e, 0x0a, 0x0f, 0x53, 0x68, 0x6f, 0x70, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x15, 0x0a, 0x05,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x8f, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x22, 0x34, 0x0a, 0x19, 0x53, 0x6b, 0x75, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74,
	0x6f, 0x72, 0x79, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x73, 0x6b, 0x75, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x6b, 0x75, 0x4b, 0x65, 0x79, 0x22, 0x79, 0x0a, 0x11, 0x53, 0x6b, 0x75,
	0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x17,
	0x0a, 0x07, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x6b, 0x75, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x6b, 0x75, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x6b, 0x75, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x6b, 0x75, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x15, 0x0a,
	0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x8f, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x22, 0x8d, 0x01, 0x0a, 0x1a, 0x53, 0x6b, 0x75, 0x49, 0x6e, 0x76, 0x65,
	0x6e, 0x74, 0x6f, 0x72, 0x79, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x62, 0x75, 0x73,
	0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x36, 0x0a, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x53, 0x6b, 0x75,
	0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x22, 0x31, 0x0a, 0x19, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x8d, 0x01, 0x0a, 0x1a, 0x4d, 0x65, 0x72, 0x63,
	0x68, 0x61, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f,
	0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12,
	0x36, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e,
	0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x2f, 0x0a, 0x17, 0x54, 0x72, 0x61, 0x64, 0x65,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x88, 0x01, 0x0a, 0x18, 0x54, 0x72, 0x61,
	0x64, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x62,
	0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x33,
	0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x54,
	0x72, 0x61, 0x64, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x22, 0x46, 0x0a, 0x0e, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x15, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0xe7, 0x07,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x7e, 0x0a, 0x11, 0x4d,
	0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x23, 0x0a, 0x0d, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x15, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0xe7, 0x07,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x29, 0x0a, 0x11, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x81, 0x01, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a,
	0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x32, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x62, 0x75,
	0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x50, 0x0a, 0x0d, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x15, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0xe7,
	0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x50, 0x0a, 0x0e,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x52,
	0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x2a, 0xc8,
	0x01, 0x0a, 0x07, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55,
	0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x10, 0xf4, 0x03, 0x12, 0x14, 0x0a, 0x0e, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4e, 0x4f, 0x54, 0x5f,
	0x45, 0x58, 0x49, 0x53, 0x54, 0x10, 0xd1, 0x86, 0x03, 0x12, 0x10, 0x0a, 0x0a, 0x55, 0x53, 0x45,
	0x52, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x10, 0xd2, 0x86, 0x03, 0x12, 0x18, 0x0a, 0x12, 0x4d,
	0x45, 0x52, 0x43, 0x48, 0x41, 0x4e, 0x54, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x45, 0x58, 0x49, 0x53,
	0x54, 0x10, 0xd3, 0x86, 0x03, 0x12, 0x14, 0x0a, 0x0e, 0x4d, 0x45, 0x52, 0x43, 0x48, 0x41, 0x4e,
	0x54, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x10, 0xd4, 0x86, 0x03, 0x12, 0x14, 0x0a, 0x0e, 0x53,
	0x48, 0x4f, 0x50, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x10, 0xd5, 0x86,
	0x03, 0x12, 0x10, 0x0a, 0x0a, 0x53, 0x48, 0x4f, 0x50, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x10,
	0xd6, 0x86, 0x03, 0x12, 0x13, 0x0a, 0x0d, 0x53, 0x4b, 0x55, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x45,
	0x58, 0x49, 0x53, 0x54, 0x10, 0xd7, 0x86, 0x03, 0x12, 0x0f, 0x0a, 0x09, 0x53, 0x4b, 0x55, 0x5f,
	0x45, 0x58, 0x49, 0x53, 0x54, 0x10, 0xd8, 0x86, 0x03, 0x2a, 0x4c, 0x0a, 0x0d, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x52,
	0x45, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45,
	0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x02, 0x12, 0x09,
	0x0a, 0x05, 0x41, 0x55, 0x44, 0x49, 0x54, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x55, 0x54,
	0x5f, 0x41, 0x57, 0x41, 0x59, 0x10, 0x04, 0x32, 0xa0, 0x05, 0x0a, 0x15, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x8f, 0x01, 0x0a, 0x12, 0x53, 0x6b, 0x75, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f,
	0x72, 0x79, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x2a, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x53, 0x6b, 0x75, 0x49, 0x6e,
	0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x62, 0x75,
	0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x53, 0x6b, 0x75, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74,
	0x6f, 0x72, 0x79, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x20, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x12, 0x18, 0x2f, 0x76, 0x31, 0x2f, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x73, 0x6b, 0x75, 0x5f, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74,
	0x6f, 0x72, 0x79, 0x12, 0x6e, 0x0a, 0x0a, 0x53, 0x68, 0x6f, 0x70, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x12, 0x22, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e,
	0x65, 0x73, 0x73, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x62,
	0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x11, 0x12, 0x0f, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x73,
	0x68, 0x6f, 0x70, 0x12, 0x6e, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x12, 0x22, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e,
	0x65, 0x73, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x62,
	0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x11, 0x12, 0x0f, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x12, 0x8a, 0x01, 0x0a, 0x12, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x2a, 0x2e, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x4d, 0x65, 0x72,
	0x63, 0x68, 0x61, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f,
	0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x12, 0x13, 0x2f, 0x76, 0x31,
	0x2f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74,
	0x12, 0x87, 0x01, 0x0a, 0x10, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x28, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x62,
	0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x29, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73,
	0x73, 0x2e, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x18, 0x12, 0x16, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x74,
	0x72, 0x61, 0x64, 0x65, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x3f, 0x5a, 0x3d, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x5f, 0x6d, 0x61, 0x6c, 0x6c, 0x5f, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x3b, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_micro_mall_search_proto_search_business_search_proto_rawDescOnce sync.Once
	file_proto_micro_mall_search_proto_search_business_search_proto_rawDescData = file_proto_micro_mall_search_proto_search_business_search_proto_rawDesc
)

func file_proto_micro_mall_search_proto_search_business_search_proto_rawDescGZIP() []byte {
	file_proto_micro_mall_search_proto_search_business_search_proto_rawDescOnce.Do(func() {
		file_proto_micro_mall_search_proto_search_business_search_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_micro_mall_search_proto_search_business_search_proto_rawDescData)
	})
	return file_proto_micro_mall_search_proto_search_business_search_proto_rawDescData
}

var file_proto_micro_mall_search_proto_search_business_search_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_micro_mall_search_proto_search_business_search_proto_goTypes = []interface{}{
	(RetCode)(0),                       // 0: search_business.RetCode
	(OperationType)(0),                 // 1: search_business.OperationType
	(*ShopSearchRequest)(nil),          // 2: search_business.ShopSearchRequest
	(*ShopSearchResponse)(nil),         // 3: search_business.ShopSearchResponse
	(*ShopSearchEntry)(nil),            // 4: search_business.ShopSearchEntry
	(*SkuInventorySearchRequest)(nil),  // 5: search_business.SkuInventorySearchRequest
	(*SkuInventoryEntry)(nil),          // 6: search_business.SkuInventoryEntry
	(*SkuInventorySearchResponse)(nil), // 7: search_business.SkuInventorySearchResponse
	(*MerchantInfoSearchRequest)(nil),  // 8: search_business.MerchantInfoSearchRequest
	(*MerchantInfoSearchResponse)(nil), // 9: search_business.MerchantInfoSearchResponse
	(*TradeOrderSearchRequest)(nil),    // 10: search_business.TradeOrderSearchRequest
	(*TradeOrderSearchResponse)(nil),   // 11: search_business.TradeOrderSearchResponse
	(*TradeOrderInfo)(nil),             // 12: search_business.TradeOrderInfo
	(*MerchantInfoEntry)(nil),          // 13: search_business.MerchantInfoEntry
	(*UserSearchRequest)(nil),          // 14: search_business.UserSearchRequest
	(*UserSearchResponse)(nil),         // 15: search_business.UserSearchResponse
	(*UserInfoEntry)(nil),              // 16: search_business.UserInfoEntry
	(*CommonResponse)(nil),             // 17: search_business.CommonResponse
}
var file_proto_micro_mall_search_proto_search_business_search_proto_depIdxs = []int32{
	17, // 0: search_business.ShopSearchResponse.common:type_name -> search_business.CommonResponse
	4,  // 1: search_business.ShopSearchResponse.list:type_name -> search_business.ShopSearchEntry
	17, // 2: search_business.SkuInventorySearchResponse.common:type_name -> search_business.CommonResponse
	6,  // 3: search_business.SkuInventorySearchResponse.list:type_name -> search_business.SkuInventoryEntry
	17, // 4: search_business.MerchantInfoSearchResponse.common:type_name -> search_business.CommonResponse
	13, // 5: search_business.MerchantInfoSearchResponse.list:type_name -> search_business.MerchantInfoEntry
	17, // 6: search_business.TradeOrderSearchResponse.common:type_name -> search_business.CommonResponse
	12, // 7: search_business.TradeOrderSearchResponse.list:type_name -> search_business.TradeOrderInfo
	17, // 8: search_business.UserSearchResponse.common:type_name -> search_business.CommonResponse
	16, // 9: search_business.UserSearchResponse.list:type_name -> search_business.UserInfoEntry
	0,  // 10: search_business.CommonResponse.code:type_name -> search_business.RetCode
	5,  // 11: search_business.SearchBusinessService.SkuInventorySearch:input_type -> search_business.SkuInventorySearchRequest
	2,  // 12: search_business.SearchBusinessService.ShopSearch:input_type -> search_business.ShopSearchRequest
	14, // 13: search_business.SearchBusinessService.UserSearch:input_type -> search_business.UserSearchRequest
	8,  // 14: search_business.SearchBusinessService.MerchantInfoSearch:input_type -> search_business.MerchantInfoSearchRequest
	10, // 15: search_business.SearchBusinessService.TradeOrderSearch:input_type -> search_business.TradeOrderSearchRequest
	7,  // 16: search_business.SearchBusinessService.SkuInventorySearch:output_type -> search_business.SkuInventorySearchResponse
	3,  // 17: search_business.SearchBusinessService.ShopSearch:output_type -> search_business.ShopSearchResponse
	15, // 18: search_business.SearchBusinessService.UserSearch:output_type -> search_business.UserSearchResponse
	9,  // 19: search_business.SearchBusinessService.MerchantInfoSearch:output_type -> search_business.MerchantInfoSearchResponse
	11, // 20: search_business.SearchBusinessService.TradeOrderSearch:output_type -> search_business.TradeOrderSearchResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_micro_mall_search_proto_search_business_search_proto_init() }
func file_proto_micro_mall_search_proto_search_business_search_proto_init() {
	if File_proto_micro_mall_search_proto_search_business_search_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopSearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopSearchEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkuInventorySearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkuInventoryEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkuInventorySearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MerchantInfoSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MerchantInfoSearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TradeOrderSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TradeOrderSearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TradeOrderInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MerchantInfoEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfoEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_micro_mall_search_proto_search_business_search_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_micro_mall_search_proto_search_business_search_proto_goTypes,
		DependencyIndexes: file_proto_micro_mall_search_proto_search_business_search_proto_depIdxs,
		EnumInfos:         file_proto_micro_mall_search_proto_search_business_search_proto_enumTypes,
		MessageInfos:      file_proto_micro_mall_search_proto_search_business_search_proto_msgTypes,
	}.Build()
	File_proto_micro_mall_search_proto_search_business_search_proto = out.File
	file_proto_micro_mall_search_proto_search_business_search_proto_rawDesc = nil
	file_proto_micro_mall_search_proto_search_business_search_proto_goTypes = nil
	file_proto_micro_mall_search_proto_search_business_search_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SearchBusinessServiceClient is the client API for SearchBusinessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchBusinessServiceClient interface {
	// 商品库存搜索
	SkuInventorySearch(ctx context.Context, in *SkuInventorySearchRequest, opts ...grpc.CallOption) (*SkuInventorySearchResponse, error)
	// 店铺搜索
	ShopSearch(ctx context.Context, in *ShopSearchRequest, opts ...grpc.CallOption) (*ShopSearchResponse, error)
	// 用户搜素
	UserSearch(ctx context.Context, in *UserSearchRequest, opts ...grpc.CallOption) (*UserSearchResponse, error)
	// 商户搜索
	MerchantInfoSearch(ctx context.Context, in *MerchantInfoSearchRequest, opts ...grpc.CallOption) (*MerchantInfoSearchResponse, error)
	// 交易订单搜索
	TradeOrderSearch(ctx context.Context, in *TradeOrderSearchRequest, opts ...grpc.CallOption) (*TradeOrderSearchResponse, error)
}

type searchBusinessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchBusinessServiceClient(cc grpc.ClientConnInterface) SearchBusinessServiceClient {
	return &searchBusinessServiceClient{cc}
}

func (c *searchBusinessServiceClient) SkuInventorySearch(ctx context.Context, in *SkuInventorySearchRequest, opts ...grpc.CallOption) (*SkuInventorySearchResponse, error) {
	out := new(SkuInventorySearchResponse)
	err := c.cc.Invoke(ctx, "/search_business.SearchBusinessService/SkuInventorySearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchBusinessServiceClient) ShopSearch(ctx context.Context, in *ShopSearchRequest, opts ...grpc.CallOption) (*ShopSearchResponse, error) {
	out := new(ShopSearchResponse)
	err := c.cc.Invoke(ctx, "/search_business.SearchBusinessService/ShopSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchBusinessServiceClient) UserSearch(ctx context.Context, in *UserSearchRequest, opts ...grpc.CallOption) (*UserSearchResponse, error) {
	out := new(UserSearchResponse)
	err := c.cc.Invoke(ctx, "/search_business.SearchBusinessService/UserSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchBusinessServiceClient) MerchantInfoSearch(ctx context.Context, in *MerchantInfoSearchRequest, opts ...grpc.CallOption) (*MerchantInfoSearchResponse, error) {
	out := new(MerchantInfoSearchResponse)
	err := c.cc.Invoke(ctx, "/search_business.SearchBusinessService/MerchantInfoSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchBusinessServiceClient) TradeOrderSearch(ctx context.Context, in *TradeOrderSearchRequest, opts ...grpc.CallOption) (*TradeOrderSearchResponse, error) {
	out := new(TradeOrderSearchResponse)
	err := c.cc.Invoke(ctx, "/search_business.SearchBusinessService/TradeOrderSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchBusinessServiceServer is the server API for SearchBusinessService service.
type SearchBusinessServiceServer interface {
	// 商品库存搜索
	SkuInventorySearch(context.Context, *SkuInventorySearchRequest) (*SkuInventorySearchResponse, error)
	// 店铺搜索
	ShopSearch(context.Context, *ShopSearchRequest) (*ShopSearchResponse, error)
	// 用户搜素
	UserSearch(context.Context, *UserSearchRequest) (*UserSearchResponse, error)
	// 商户搜索
	MerchantInfoSearch(context.Context, *MerchantInfoSearchRequest) (*MerchantInfoSearchResponse, error)
	// 交易订单搜索
	TradeOrderSearch(context.Context, *TradeOrderSearchRequest) (*TradeOrderSearchResponse, error)
}

// UnimplementedSearchBusinessServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSearchBusinessServiceServer struct {
}

func (*UnimplementedSearchBusinessServiceServer) SkuInventorySearch(context.Context, *SkuInventorySearchRequest) (*SkuInventorySearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SkuInventorySearch not implemented")
}
func (*UnimplementedSearchBusinessServiceServer) ShopSearch(context.Context, *ShopSearchRequest) (*ShopSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShopSearch not implemented")
}
func (*UnimplementedSearchBusinessServiceServer) UserSearch(context.Context, *UserSearchRequest) (*UserSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserSearch not implemented")
}
func (*UnimplementedSearchBusinessServiceServer) MerchantInfoSearch(context.Context, *MerchantInfoSearchRequest) (*MerchantInfoSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MerchantInfoSearch not implemented")
}
func (*UnimplementedSearchBusinessServiceServer) TradeOrderSearch(context.Context, *TradeOrderSearchRequest) (*TradeOrderSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TradeOrderSearch not implemented")
}

func RegisterSearchBusinessServiceServer(s *grpc.Server, srv SearchBusinessServiceServer) {
	s.RegisterService(&_SearchBusinessService_serviceDesc, srv)
}

func _SearchBusinessService_SkuInventorySearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkuInventorySearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchBusinessServiceServer).SkuInventorySearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search_business.SearchBusinessService/SkuInventorySearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchBusinessServiceServer).SkuInventorySearch(ctx, req.(*SkuInventorySearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchBusinessService_ShopSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShopSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchBusinessServiceServer).ShopSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search_business.SearchBusinessService/ShopSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchBusinessServiceServer).ShopSearch(ctx, req.(*ShopSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchBusinessService_UserSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchBusinessServiceServer).UserSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search_business.SearchBusinessService/UserSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchBusinessServiceServer).UserSearch(ctx, req.(*UserSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchBusinessService_MerchantInfoSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantInfoSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchBusinessServiceServer).MerchantInfoSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search_business.SearchBusinessService/MerchantInfoSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchBusinessServiceServer).MerchantInfoSearch(ctx, req.(*MerchantInfoSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchBusinessService_TradeOrderSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradeOrderSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchBusinessServiceServer).TradeOrderSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search_business.SearchBusinessService/TradeOrderSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchBusinessServiceServer).TradeOrderSearch(ctx, req.(*TradeOrderSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SearchBusinessService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "search_business.SearchBusinessService",
	HandlerType: (*SearchBusinessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SkuInventorySearch",
			Handler:    _SearchBusinessService_SkuInventorySearch_Handler,
		},
		{
			MethodName: "ShopSearch",
			Handler:    _SearchBusinessService_ShopSearch_Handler,
		},
		{
			MethodName: "UserSearch",
			Handler:    _SearchBusinessService_UserSearch_Handler,
		},
		{
			MethodName: "MerchantInfoSearch",
			Handler:    _SearchBusinessService_MerchantInfoSearch_Handler,
		},
		{
			MethodName: "TradeOrderSearch",
			Handler:    _SearchBusinessService_TradeOrderSearch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/micro_mall_search_proto/search_business/search.proto",
}
