// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/micro_mall_users_proto/users/users.proto

package users

import (
	context "context"
	fmt "fmt"
	_ "gitee.com/kelvins-io/common/proto/google/api"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RetCode int32

const (
	RetCode_SUCCESS            RetCode = 0
	RetCode_ERROR              RetCode = 500
	RetCode_USER_NOT_EXIST     RetCode = 50001
	RetCode_USER_EXIST         RetCode = 50002
	RetCode_MERCHANT_NOT_EXIST RetCode = 50003
	RetCode_MERCHANT_EXIST     RetCode = 50004
	RetCode_ACCOUNT_EXIST      RetCode = 50005
	RetCode_ACCOUNT_NOT_EXIST  RetCode = 50006
)

var RetCode_name = map[int32]string{
	0:     "SUCCESS",
	500:   "ERROR",
	50001: "USER_NOT_EXIST",
	50002: "USER_EXIST",
	50003: "MERCHANT_NOT_EXIST",
	50004: "MERCHANT_EXIST",
	50005: "ACCOUNT_EXIST",
	50006: "ACCOUNT_NOT_EXIST",
}

var RetCode_value = map[string]int32{
	"SUCCESS":            0,
	"ERROR":              500,
	"USER_NOT_EXIST":     50001,
	"USER_EXIST":         50002,
	"MERCHANT_NOT_EXIST": 50003,
	"MERCHANT_EXIST":     50004,
	"ACCOUNT_EXIST":      50005,
	"ACCOUNT_NOT_EXIST":  50006,
}

func (x RetCode) String() string {
	return proto.EnumName(RetCode_name, int32(x))
}

func (RetCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{0}
}

type OperationType int32

const (
	OperationType_CREATE OperationType = 0
	OperationType_UPDATE OperationType = 1
	OperationType_DELETE OperationType = 2
	OperationType_AUDIT  OperationType = 3
)

var OperationType_name = map[int32]string{
	0: "CREATE",
	1: "UPDATE",
	2: "DELETE",
	3: "AUDIT",
}

var OperationType_value = map[string]int32{
	"CREATE": 0,
	"UPDATE": 1,
	"DELETE": 2,
	"AUDIT":  3,
}

func (x OperationType) String() string {
	return proto.EnumName(OperationType_name, int32(x))
}

func (OperationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{1}
}

type CoinType int32

const (
	CoinType_CNY CoinType = 0
	CoinType_USD CoinType = 1
)

var CoinType_name = map[int32]string{
	0: "CNY",
	1: "USD",
}

var CoinType_value = map[string]int32{
	"CNY": 0,
	"USD": 1,
}

func (x CoinType) String() string {
	return proto.EnumName(CoinType_name, int32(x))
}

func (CoinType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{2}
}

type AccountState int32

const (
	AccountState_NORMAL  AccountState = 0
	AccountState_LOCK    AccountState = 1
	AccountState_INVALID AccountState = 2
)

var AccountState_name = map[int32]string{
	0: "NORMAL",
	1: "LOCK",
	2: "INVALID",
}

var AccountState_value = map[string]int32{
	"NORMAL":  0,
	"LOCK":    1,
	"INVALID": 2,
}

func (x AccountState) String() string {
	return proto.EnumName(AccountState_name, int32(x))
}

func (AccountState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{3}
}

type AccountType int32

const (
	AccountType_PERSONAL AccountType = 0
	AccountType_COMPANY  AccountType = 1
	AccountType_SYSTEM   AccountType = 2
)

var AccountType_name = map[int32]string{
	0: "PERSONAL",
	1: "COMPANY",
	2: "SYSTEM",
}

var AccountType_value = map[string]int32{
	"PERSONAL": 0,
	"COMPANY":  1,
	"SYSTEM":   2,
}

func (x AccountType) String() string {
	return proto.EnumName(AccountType_name, int32(x))
}

func (AccountType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{4}
}

type CreateUserAccountRequest struct {
	Uid                  int64        `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Balance              string       `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	CoinType             CoinType     `protobuf:"varint,3,opt,name=coin_type,json=coinType,proto3,enum=users.CoinType" json:"coin_type,omitempty"`
	CoinDesc             string       `protobuf:"bytes,4,opt,name=coin_desc,json=coinDesc,proto3" json:"coin_desc,omitempty"`
	AccountState         AccountState `protobuf:"varint,5,opt,name=account_state,json=accountState,proto3,enum=users.AccountState" json:"account_state,omitempty"`
	AccountType          AccountType  `protobuf:"varint,6,opt,name=account_type,json=accountType,proto3,enum=users.AccountType" json:"account_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateUserAccountRequest) Reset()         { *m = CreateUserAccountRequest{} }
func (m *CreateUserAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserAccountRequest) ProtoMessage()    {}
func (*CreateUserAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{0}
}

func (m *CreateUserAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserAccountRequest.Unmarshal(m, b)
}
func (m *CreateUserAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserAccountRequest.Merge(m, src)
}
func (m *CreateUserAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserAccountRequest.Size(m)
}
func (m *CreateUserAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserAccountRequest proto.InternalMessageInfo

func (m *CreateUserAccountRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CreateUserAccountRequest) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *CreateUserAccountRequest) GetCoinType() CoinType {
	if m != nil {
		return m.CoinType
	}
	return CoinType_CNY
}

func (m *CreateUserAccountRequest) GetCoinDesc() string {
	if m != nil {
		return m.CoinDesc
	}
	return ""
}

func (m *CreateUserAccountRequest) GetAccountState() AccountState {
	if m != nil {
		return m.AccountState
	}
	return AccountState_NORMAL
}

func (m *CreateUserAccountRequest) GetAccountType() AccountType {
	if m != nil {
		return m.AccountType
	}
	return AccountType_PERSONAL
}

type CreateUserAccountResponse struct {
	Common               *CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	AccountCode          string          `protobuf:"bytes,2,opt,name=account_code,json=accountCode,proto3" json:"account_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateUserAccountResponse) Reset()         { *m = CreateUserAccountResponse{} }
func (m *CreateUserAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserAccountResponse) ProtoMessage()    {}
func (*CreateUserAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{1}
}

func (m *CreateUserAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserAccountResponse.Unmarshal(m, b)
}
func (m *CreateUserAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserAccountResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserAccountResponse.Merge(m, src)
}
func (m *CreateUserAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserAccountResponse.Size(m)
}
func (m *CreateUserAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserAccountResponse proto.InternalMessageInfo

func (m *CreateUserAccountResponse) GetCommon() *CommonResponse {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *CreateUserAccountResponse) GetAccountCode() string {
	if m != nil {
		return m.AccountCode
	}
	return ""
}

type GetUserInfoByPhoneRequest struct {
	CountryCode          string   `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoByPhoneRequest) Reset()         { *m = GetUserInfoByPhoneRequest{} }
func (m *GetUserInfoByPhoneRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoByPhoneRequest) ProtoMessage()    {}
func (*GetUserInfoByPhoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{2}
}

func (m *GetUserInfoByPhoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoByPhoneRequest.Unmarshal(m, b)
}
func (m *GetUserInfoByPhoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoByPhoneRequest.Marshal(b, m, deterministic)
}
func (m *GetUserInfoByPhoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoByPhoneRequest.Merge(m, src)
}
func (m *GetUserInfoByPhoneRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoByPhoneRequest.Size(m)
}
func (m *GetUserInfoByPhoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoByPhoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoByPhoneRequest proto.InternalMessageInfo

func (m *GetUserInfoByPhoneRequest) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *GetUserInfoByPhoneRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type GetUserInfoByPhoneResponse struct {
	Common               *CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Info                 *UserInfo       `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetUserInfoByPhoneResponse) Reset()         { *m = GetUserInfoByPhoneResponse{} }
func (m *GetUserInfoByPhoneResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoByPhoneResponse) ProtoMessage()    {}
func (*GetUserInfoByPhoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{3}
}

func (m *GetUserInfoByPhoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoByPhoneResponse.Unmarshal(m, b)
}
func (m *GetUserInfoByPhoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoByPhoneResponse.Marshal(b, m, deterministic)
}
func (m *GetUserInfoByPhoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoByPhoneResponse.Merge(m, src)
}
func (m *GetUserInfoByPhoneResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoByPhoneResponse.Size(m)
}
func (m *GetUserInfoByPhoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoByPhoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoByPhoneResponse proto.InternalMessageInfo

func (m *GetUserInfoByPhoneResponse) GetCommon() *CommonResponse {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *GetUserInfoByPhoneResponse) GetInfo() *UserInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type GetUserInfoRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoRequest) Reset()         { *m = GetUserInfoRequest{} }
func (m *GetUserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoRequest) ProtoMessage()    {}
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{4}
}

func (m *GetUserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoRequest.Unmarshal(m, b)
}
func (m *GetUserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetUserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoRequest.Merge(m, src)
}
func (m *GetUserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoRequest.Size(m)
}
func (m *GetUserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoRequest proto.InternalMessageInfo

func (m *GetUserInfoRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type UserInfo struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	AccountId            string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	UserName             string   `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Sex                  int32    `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty"`
	CountryCode          string   `protobuf:"bytes,5,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Phone                string   `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	State                int32    `protobuf:"varint,8,opt,name=state,proto3" json:"state,omitempty"`
	IdCardNo             string   `protobuf:"bytes,9,opt,name=id_card_no,json=idCardNo,proto3" json:"id_card_no,omitempty"`
	Inviter              int64    `protobuf:"varint,10,opt,name=inviter,proto3" json:"inviter,omitempty"`
	InviterCode          string   `protobuf:"bytes,11,opt,name=inviter_code,json=inviterCode,proto3" json:"inviter_code,omitempty"`
	ContactAddr          string   `protobuf:"bytes,12,opt,name=contact_addr,json=contactAddr,proto3" json:"contact_addr,omitempty"`
	Age                  int32    `protobuf:"varint,13,opt,name=age,proto3" json:"age,omitempty"`
	CreateTime           string   `protobuf:"bytes,14,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,15,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{5}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserInfo) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *UserInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserInfo) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *UserInfo) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *UserInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInfo) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *UserInfo) GetIdCardNo() string {
	if m != nil {
		return m.IdCardNo
	}
	return ""
}

func (m *UserInfo) GetInviter() int64 {
	if m != nil {
		return m.Inviter
	}
	return 0
}

func (m *UserInfo) GetInviterCode() string {
	if m != nil {
		return m.InviterCode
	}
	return ""
}

func (m *UserInfo) GetContactAddr() string {
	if m != nil {
		return m.ContactAddr
	}
	return ""
}

func (m *UserInfo) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UserInfo) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *UserInfo) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

type GetUserInfoResponse struct {
	Common               *CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Info                 *UserInfo       `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetUserInfoResponse) Reset()         { *m = GetUserInfoResponse{} }
func (m *GetUserInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoResponse) ProtoMessage()    {}
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{6}
}

func (m *GetUserInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoResponse.Unmarshal(m, b)
}
func (m *GetUserInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetUserInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoResponse.Merge(m, src)
}
func (m *GetUserInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoResponse.Size(m)
}
func (m *GetUserInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoResponse proto.InternalMessageInfo

func (m *GetUserInfoResponse) GetCommon() *CommonResponse {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *GetUserInfoResponse) GetInfo() *UserInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type MerchantsMaterialInfo struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	MaterialId           int64    `protobuf:"varint,2,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	RegisterAddr         string   `protobuf:"bytes,3,opt,name=register_addr,json=registerAddr,proto3" json:"register_addr,omitempty"`
	HealthCardNo         string   `protobuf:"bytes,4,opt,name=health_card_no,json=healthCardNo,proto3" json:"health_card_no,omitempty"`
	Identity             int32    `protobuf:"varint,5,opt,name=identity,proto3" json:"identity,omitempty"`
	State                int32    `protobuf:"varint,6,opt,name=state,proto3" json:"state,omitempty"`
	TaxCardNo            string   `protobuf:"bytes,7,opt,name=tax_card_no,json=taxCardNo,proto3" json:"tax_card_no,omitempty"`
	CreateTime           string   `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           string   `protobuf:"bytes,9,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantsMaterialInfo) Reset()         { *m = MerchantsMaterialInfo{} }
func (m *MerchantsMaterialInfo) String() string { return proto.CompactTextString(m) }
func (*MerchantsMaterialInfo) ProtoMessage()    {}
func (*MerchantsMaterialInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{7}
}

func (m *MerchantsMaterialInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantsMaterialInfo.Unmarshal(m, b)
}
func (m *MerchantsMaterialInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantsMaterialInfo.Marshal(b, m, deterministic)
}
func (m *MerchantsMaterialInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantsMaterialInfo.Merge(m, src)
}
func (m *MerchantsMaterialInfo) XXX_Size() int {
	return xxx_messageInfo_MerchantsMaterialInfo.Size(m)
}
func (m *MerchantsMaterialInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantsMaterialInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantsMaterialInfo proto.InternalMessageInfo

func (m *MerchantsMaterialInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *MerchantsMaterialInfo) GetMaterialId() int64 {
	if m != nil {
		return m.MaterialId
	}
	return 0
}

func (m *MerchantsMaterialInfo) GetRegisterAddr() string {
	if m != nil {
		return m.RegisterAddr
	}
	return ""
}

func (m *MerchantsMaterialInfo) GetHealthCardNo() string {
	if m != nil {
		return m.HealthCardNo
	}
	return ""
}

func (m *MerchantsMaterialInfo) GetIdentity() int32 {
	if m != nil {
		return m.Identity
	}
	return 0
}

func (m *MerchantsMaterialInfo) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *MerchantsMaterialInfo) GetTaxCardNo() string {
	if m != nil {
		return m.TaxCardNo
	}
	return ""
}

func (m *MerchantsMaterialInfo) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *MerchantsMaterialInfo) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

type MerchantsMaterialRequest struct {
	Info                 *MerchantsMaterialInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	OperationType        OperationType          `protobuf:"varint,2,opt,name=operation_type,json=operationType,proto3,enum=users.OperationType" json:"operation_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *MerchantsMaterialRequest) Reset()         { *m = MerchantsMaterialRequest{} }
func (m *MerchantsMaterialRequest) String() string { return proto.CompactTextString(m) }
func (*MerchantsMaterialRequest) ProtoMessage()    {}
func (*MerchantsMaterialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{8}
}

func (m *MerchantsMaterialRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantsMaterialRequest.Unmarshal(m, b)
}
func (m *MerchantsMaterialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantsMaterialRequest.Marshal(b, m, deterministic)
}
func (m *MerchantsMaterialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantsMaterialRequest.Merge(m, src)
}
func (m *MerchantsMaterialRequest) XXX_Size() int {
	return xxx_messageInfo_MerchantsMaterialRequest.Size(m)
}
func (m *MerchantsMaterialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantsMaterialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantsMaterialRequest proto.InternalMessageInfo

func (m *MerchantsMaterialRequest) GetInfo() *MerchantsMaterialInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *MerchantsMaterialRequest) GetOperationType() OperationType {
	if m != nil {
		return m.OperationType
	}
	return OperationType_CREATE
}

type MerchantsMaterialResponse struct {
	Common               *CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	MaterialId           int64           `protobuf:"varint,2,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MerchantsMaterialResponse) Reset()         { *m = MerchantsMaterialResponse{} }
func (m *MerchantsMaterialResponse) String() string { return proto.CompactTextString(m) }
func (*MerchantsMaterialResponse) ProtoMessage()    {}
func (*MerchantsMaterialResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{9}
}

func (m *MerchantsMaterialResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantsMaterialResponse.Unmarshal(m, b)
}
func (m *MerchantsMaterialResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantsMaterialResponse.Marshal(b, m, deterministic)
}
func (m *MerchantsMaterialResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantsMaterialResponse.Merge(m, src)
}
func (m *MerchantsMaterialResponse) XXX_Size() int {
	return xxx_messageInfo_MerchantsMaterialResponse.Size(m)
}
func (m *MerchantsMaterialResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantsMaterialResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantsMaterialResponse proto.InternalMessageInfo

func (m *MerchantsMaterialResponse) GetCommon() *CommonResponse {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *MerchantsMaterialResponse) GetMaterialId() int64 {
	if m != nil {
		return m.MaterialId
	}
	return 0
}

type GetMerchantsMaterialRequest struct {
	MaterialId           int64    `protobuf:"varint,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMerchantsMaterialRequest) Reset()         { *m = GetMerchantsMaterialRequest{} }
func (m *GetMerchantsMaterialRequest) String() string { return proto.CompactTextString(m) }
func (*GetMerchantsMaterialRequest) ProtoMessage()    {}
func (*GetMerchantsMaterialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{10}
}

func (m *GetMerchantsMaterialRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMerchantsMaterialRequest.Unmarshal(m, b)
}
func (m *GetMerchantsMaterialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMerchantsMaterialRequest.Marshal(b, m, deterministic)
}
func (m *GetMerchantsMaterialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMerchantsMaterialRequest.Merge(m, src)
}
func (m *GetMerchantsMaterialRequest) XXX_Size() int {
	return xxx_messageInfo_GetMerchantsMaterialRequest.Size(m)
}
func (m *GetMerchantsMaterialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMerchantsMaterialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMerchantsMaterialRequest proto.InternalMessageInfo

func (m *GetMerchantsMaterialRequest) GetMaterialId() int64 {
	if m != nil {
		return m.MaterialId
	}
	return 0
}

type GetMerchantsMaterialResponse struct {
	Common               *CommonResponse        `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Info                 *MerchantsMaterialInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetMerchantsMaterialResponse) Reset()         { *m = GetMerchantsMaterialResponse{} }
func (m *GetMerchantsMaterialResponse) String() string { return proto.CompactTextString(m) }
func (*GetMerchantsMaterialResponse) ProtoMessage()    {}
func (*GetMerchantsMaterialResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{11}
}

func (m *GetMerchantsMaterialResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMerchantsMaterialResponse.Unmarshal(m, b)
}
func (m *GetMerchantsMaterialResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMerchantsMaterialResponse.Marshal(b, m, deterministic)
}
func (m *GetMerchantsMaterialResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMerchantsMaterialResponse.Merge(m, src)
}
func (m *GetMerchantsMaterialResponse) XXX_Size() int {
	return xxx_messageInfo_GetMerchantsMaterialResponse.Size(m)
}
func (m *GetMerchantsMaterialResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMerchantsMaterialResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMerchantsMaterialResponse proto.InternalMessageInfo

func (m *GetMerchantsMaterialResponse) GetCommon() *CommonResponse {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *GetMerchantsMaterialResponse) GetInfo() *MerchantsMaterialInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type MerchantsAssociateShopRequest struct {
	MaterialId           int64    `protobuf:"varint,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	ShopId               int64    `protobuf:"varint,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	IsAssociate          bool     `protobuf:"varint,3,opt,name=is_associate,json=isAssociate,proto3" json:"is_associate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantsAssociateShopRequest) Reset()         { *m = MerchantsAssociateShopRequest{} }
func (m *MerchantsAssociateShopRequest) String() string { return proto.CompactTextString(m) }
func (*MerchantsAssociateShopRequest) ProtoMessage()    {}
func (*MerchantsAssociateShopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{12}
}

func (m *MerchantsAssociateShopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantsAssociateShopRequest.Unmarshal(m, b)
}
func (m *MerchantsAssociateShopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantsAssociateShopRequest.Marshal(b, m, deterministic)
}
func (m *MerchantsAssociateShopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantsAssociateShopRequest.Merge(m, src)
}
func (m *MerchantsAssociateShopRequest) XXX_Size() int {
	return xxx_messageInfo_MerchantsAssociateShopRequest.Size(m)
}
func (m *MerchantsAssociateShopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantsAssociateShopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantsAssociateShopRequest proto.InternalMessageInfo

func (m *MerchantsAssociateShopRequest) GetMaterialId() int64 {
	if m != nil {
		return m.MaterialId
	}
	return 0
}

func (m *MerchantsAssociateShopRequest) GetShopId() int64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *MerchantsAssociateShopRequest) GetIsAssociate() bool {
	if m != nil {
		return m.IsAssociate
	}
	return false
}

type MerchantsAssociateShopResponse struct {
	Common               *CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MerchantsAssociateShopResponse) Reset()         { *m = MerchantsAssociateShopResponse{} }
func (m *MerchantsAssociateShopResponse) String() string { return proto.CompactTextString(m) }
func (*MerchantsAssociateShopResponse) ProtoMessage()    {}
func (*MerchantsAssociateShopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{13}
}

func (m *MerchantsAssociateShopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantsAssociateShopResponse.Unmarshal(m, b)
}
func (m *MerchantsAssociateShopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantsAssociateShopResponse.Marshal(b, m, deterministic)
}
func (m *MerchantsAssociateShopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantsAssociateShopResponse.Merge(m, src)
}
func (m *MerchantsAssociateShopResponse) XXX_Size() int {
	return xxx_messageInfo_MerchantsAssociateShopResponse.Size(m)
}
func (m *MerchantsAssociateShopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantsAssociateShopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantsAssociateShopResponse proto.InternalMessageInfo

func (m *MerchantsAssociateShopResponse) GetCommon() *CommonResponse {
	if m != nil {
		return m.Common
	}
	return nil
}

type MerchantsMaterialAuditRequest struct {
	MaterialId           int64    `protobuf:"varint,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	AuditUid             int64    `protobuf:"varint,2,opt,name=audit_uid,json=auditUid,proto3" json:"audit_uid,omitempty"`
	Comment              string   `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantsMaterialAuditRequest) Reset()         { *m = MerchantsMaterialAuditRequest{} }
func (m *MerchantsMaterialAuditRequest) String() string { return proto.CompactTextString(m) }
func (*MerchantsMaterialAuditRequest) ProtoMessage()    {}
func (*MerchantsMaterialAuditRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{14}
}

func (m *MerchantsMaterialAuditRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantsMaterialAuditRequest.Unmarshal(m, b)
}
func (m *MerchantsMaterialAuditRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantsMaterialAuditRequest.Marshal(b, m, deterministic)
}
func (m *MerchantsMaterialAuditRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantsMaterialAuditRequest.Merge(m, src)
}
func (m *MerchantsMaterialAuditRequest) XXX_Size() int {
	return xxx_messageInfo_MerchantsMaterialAuditRequest.Size(m)
}
func (m *MerchantsMaterialAuditRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantsMaterialAuditRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantsMaterialAuditRequest proto.InternalMessageInfo

func (m *MerchantsMaterialAuditRequest) GetMaterialId() int64 {
	if m != nil {
		return m.MaterialId
	}
	return 0
}

func (m *MerchantsMaterialAuditRequest) GetAuditUid() int64 {
	if m != nil {
		return m.AuditUid
	}
	return 0
}

func (m *MerchantsMaterialAuditRequest) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type MerchantsMaterialAuditResponse struct {
	Common               *CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	State                int32           `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	Comment              string          `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	NextAuditUid         int64           `protobuf:"varint,4,opt,name=next_audit_uid,json=nextAuditUid,proto3" json:"next_audit_uid,omitempty"`
	IsOver               bool            `protobuf:"varint,5,opt,name=is_over,json=isOver,proto3" json:"is_over,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MerchantsMaterialAuditResponse) Reset()         { *m = MerchantsMaterialAuditResponse{} }
func (m *MerchantsMaterialAuditResponse) String() string { return proto.CompactTextString(m) }
func (*MerchantsMaterialAuditResponse) ProtoMessage()    {}
func (*MerchantsMaterialAuditResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{15}
}

func (m *MerchantsMaterialAuditResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantsMaterialAuditResponse.Unmarshal(m, b)
}
func (m *MerchantsMaterialAuditResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantsMaterialAuditResponse.Marshal(b, m, deterministic)
}
func (m *MerchantsMaterialAuditResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantsMaterialAuditResponse.Merge(m, src)
}
func (m *MerchantsMaterialAuditResponse) XXX_Size() int {
	return xxx_messageInfo_MerchantsMaterialAuditResponse.Size(m)
}
func (m *MerchantsMaterialAuditResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantsMaterialAuditResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantsMaterialAuditResponse proto.InternalMessageInfo

func (m *MerchantsMaterialAuditResponse) GetCommon() *CommonResponse {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *MerchantsMaterialAuditResponse) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *MerchantsMaterialAuditResponse) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *MerchantsMaterialAuditResponse) GetNextAuditUid() int64 {
	if m != nil {
		return m.NextAuditUid
	}
	return 0
}

func (m *MerchantsMaterialAuditResponse) GetIsOver() bool {
	if m != nil {
		return m.IsOver
	}
	return false
}

type CommonResponse struct {
	Code                 RetCode  `protobuf:"varint,1,opt,name=code,proto3,enum=users.RetCode" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonResponse) Reset()         { *m = CommonResponse{} }
func (m *CommonResponse) String() string { return proto.CompactTextString(m) }
func (*CommonResponse) ProtoMessage()    {}
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb9de2f1fdeb7bca, []int{16}
}

func (m *CommonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonResponse.Unmarshal(m, b)
}
func (m *CommonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonResponse.Marshal(b, m, deterministic)
}
func (m *CommonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonResponse.Merge(m, src)
}
func (m *CommonResponse) XXX_Size() int {
	return xxx_messageInfo_CommonResponse.Size(m)
}
func (m *CommonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommonResponse proto.InternalMessageInfo

func (m *CommonResponse) GetCode() RetCode {
	if m != nil {
		return m.Code
	}
	return RetCode_SUCCESS
}

func (m *CommonResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterEnum("users.RetCode", RetCode_name, RetCode_value)
	proto.RegisterEnum("users.OperationType", OperationType_name, OperationType_value)
	proto.RegisterEnum("users.CoinType", CoinType_name, CoinType_value)
	proto.RegisterEnum("users.AccountState", AccountState_name, AccountState_value)
	proto.RegisterEnum("users.AccountType", AccountType_name, AccountType_value)
	proto.RegisterType((*CreateUserAccountRequest)(nil), "users.CreateUserAccountRequest")
	proto.RegisterType((*CreateUserAccountResponse)(nil), "users.CreateUserAccountResponse")
	proto.RegisterType((*GetUserInfoByPhoneRequest)(nil), "users.GetUserInfoByPhoneRequest")
	proto.RegisterType((*GetUserInfoByPhoneResponse)(nil), "users.GetUserInfoByPhoneResponse")
	proto.RegisterType((*GetUserInfoRequest)(nil), "users.GetUserInfoRequest")
	proto.RegisterType((*UserInfo)(nil), "users.UserInfo")
	proto.RegisterType((*GetUserInfoResponse)(nil), "users.GetUserInfoResponse")
	proto.RegisterType((*MerchantsMaterialInfo)(nil), "users.MerchantsMaterialInfo")
	proto.RegisterType((*MerchantsMaterialRequest)(nil), "users.MerchantsMaterialRequest")
	proto.RegisterType((*MerchantsMaterialResponse)(nil), "users.MerchantsMaterialResponse")
	proto.RegisterType((*GetMerchantsMaterialRequest)(nil), "users.GetMerchantsMaterialRequest")
	proto.RegisterType((*GetMerchantsMaterialResponse)(nil), "users.GetMerchantsMaterialResponse")
	proto.RegisterType((*MerchantsAssociateShopRequest)(nil), "users.MerchantsAssociateShopRequest")
	proto.RegisterType((*MerchantsAssociateShopResponse)(nil), "users.MerchantsAssociateShopResponse")
	proto.RegisterType((*MerchantsMaterialAuditRequest)(nil), "users.MerchantsMaterialAuditRequest")
	proto.RegisterType((*MerchantsMaterialAuditResponse)(nil), "users.MerchantsMaterialAuditResponse")
	proto.RegisterType((*CommonResponse)(nil), "users.CommonResponse")
}

func init() {
	proto.RegisterFile("proto/micro_mall_users_proto/users/users.proto", fileDescriptor_eb9de2f1fdeb7bca)
}

var fileDescriptor_eb9de2f1fdeb7bca = []byte{
	// 1457 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xdd, 0x6e, 0x1b, 0xc5,
	0x17, 0xef, 0xda, 0xf1, 0xd7, 0xb1, 0xe3, 0xba, 0xd3, 0xb4, 0xd9, 0x38, 0x69, 0x9b, 0x6e, 0xfa,
	0xaf, 0x2a, 0xeb, 0xdf, 0xba, 0x0d, 0x54, 0x42, 0x45, 0xaa, 0x64, 0x1c, 0x53, 0x2c, 0x12, 0x3b,
	0x5a, 0xdb, 0x88, 0x8a, 0x8b, 0xd5, 0x64, 0x77, 0x9a, 0x8c, 0x6a, 0xef, 0x98, 0xdd, 0x75, 0x88,
	0x11, 0x02, 0xa9, 0x42, 0x91, 0xe0, 0x96, 0x5b, 0x6e, 0xb8, 0x83, 0x97, 0xe0, 0x8e, 0x07, 0x80,
	0x02, 0x0f, 0x80, 0x78, 0x04, 0x1e, 0x00, 0xcd, 0xc7, 0xae, 0xd7, 0xb5, 0x9d, 0x56, 0x91, 0xb8,
	0xb1, 0x66, 0xce, 0x9e, 0x8f, 0xdf, 0xf9, 0xcd, 0x99, 0x33, 0xc7, 0x70, 0x6f, 0xe8, 0xb1, 0x80,
	0x55, 0x07, 0xd4, 0xf6, 0x98, 0x35, 0xc0, 0xfd, 0xbe, 0x35, 0xf2, 0x89, 0xe7, 0x5b, 0x52, 0x2c,
	0xd6, 0xf2, 0x57, 0x2a, 0xa2, 0x94, 0xd8, 0x94, 0x1f, 0x1f, 0xd2, 0x80, 0x90, 0x7b, 0x36, 0x1b,
	0x54, 0x9f, 0x93, 0xfe, 0x31, 0x75, 0xfd, 0xbb, 0x94, 0x55, 0x6d, 0x36, 0x18, 0x30, 0xb7, 0x2a,
	0x6d, 0x0f, 0x19, 0x3b, 0xec, 0x93, 0x2a, 0x1e, 0xd2, 0x2a, 0x76, 0x5d, 0x16, 0xe0, 0x80, 0x32,
	0x57, 0xb9, 0x31, 0x5e, 0x24, 0x40, 0xaf, 0x7b, 0x04, 0x07, 0xa4, 0xe7, 0x13, 0xaf, 0x66, 0xdb,
	0x6c, 0xe4, 0x06, 0x26, 0xf9, 0x74, 0x44, 0xfc, 0x00, 0x95, 0x20, 0x39, 0xa2, 0x8e, 0xae, 0x6d,
	0x6a, 0x77, 0x92, 0x26, 0x5f, 0x22, 0x1d, 0x32, 0x07, 0xb8, 0x8f, 0x5d, 0x9b, 0xe8, 0x89, 0x4d,
	0xed, 0x4e, 0xce, 0x0c, 0xb7, 0xe8, 0xff, 0x90, 0xb3, 0x19, 0x75, 0xad, 0x60, 0x3c, 0x24, 0x7a,
	0x72, 0x53, 0xbb, 0x53, 0xdc, 0xbe, 0x78, 0x4f, 0x02, 0xae, 0x33, 0xea, 0x76, 0xc7, 0x43, 0x62,
	0x66, 0x6d, 0xb5, 0x42, 0xeb, 0x4a, 0xdb, 0x21, 0xbe, 0xad, 0x2f, 0x09, 0x4f, 0xe2, 0xe3, 0x0e,
	0xf1, 0x6d, 0xf4, 0x0e, 0x2c, 0x63, 0x09, 0xc4, 0xf2, 0x03, 0x1c, 0x10, 0x3d, 0x25, 0xdc, 0x5d,
	0x56, 0xee, 0x14, 0xc8, 0x0e, 0xff, 0x64, 0x16, 0x70, 0x6c, 0x87, 0x1e, 0x42, 0xb8, 0x97, 0x38,
	0xd2, 0xc2, 0x10, 0x4d, 0x1b, 0x0a, 0x28, 0x79, 0x3c, 0xd9, 0x18, 0x03, 0x58, 0x9b, 0xc3, 0x81,
	0x3f, 0x64, 0xae, 0x4f, 0xd0, 0x5d, 0x48, 0x4b, 0x3a, 0x05, 0x0f, 0xf9, 0xed, 0x2b, 0x51, 0x56,
	0x5c, 0x18, 0xaa, 0x99, 0x4a, 0x09, 0xdd, 0x9c, 0x40, 0xb0, 0x99, 0x13, 0xd2, 0x14, 0x86, 0xab,
	0x33, 0x87, 0x18, 0x5d, 0x58, 0x7b, 0x42, 0x02, 0x1e, 0xab, 0xe9, 0x3e, 0x63, 0xef, 0x8d, 0xf7,
	0x8f, 0x98, 0x4b, 0x42, 0xce, 0x6f, 0x42, 0x41, 0x68, 0x7a, 0x63, 0x69, 0xaf, 0x49, 0x7b, 0x25,
	0xe3, 0xf6, 0x68, 0x05, 0x52, 0x43, 0x6e, 0xa2, 0x7c, 0xcb, 0x8d, 0x31, 0x84, 0xf2, 0x3c, 0xaf,
	0xe7, 0xcb, 0x62, 0x0b, 0x96, 0xa8, 0xfb, 0x8c, 0x89, 0x08, 0xf9, 0xe8, 0x20, 0x43, 0xe7, 0xa6,
	0xf8, 0x68, 0xdc, 0x06, 0x14, 0x8b, 0xb8, 0xb0, 0x68, 0x8c, 0x1f, 0x92, 0x90, 0x0d, 0xb5, 0xe6,
	0xd4, 0xd4, 0x35, 0x80, 0x90, 0x31, 0xea, 0xa8, 0x9c, 0x72, 0x4a, 0xd2, 0x74, 0x78, 0xa9, 0xf0,
	0xe8, 0x96, 0x8b, 0x07, 0xb2, 0xb0, 0x72, 0x66, 0x96, 0x0b, 0x5a, 0x78, 0x40, 0xb8, 0x37, 0x9f,
	0x9c, 0x88, 0x0a, 0x4a, 0x99, 0x7c, 0x39, 0xc3, 0x5f, 0xea, 0x0c, 0xfe, 0xd2, 0x31, 0xfe, 0xb8,
	0x94, 0x0c, 0x30, 0xed, 0xeb, 0x19, 0x29, 0x15, 0x1b, 0x2e, 0x95, 0x35, 0x98, 0x15, 0x21, 0xe4,
	0x06, 0x6d, 0x00, 0x50, 0xc7, 0xb2, 0xb1, 0xe7, 0x58, 0x2e, 0xd3, 0x73, 0x12, 0x14, 0x75, 0xea,
	0xd8, 0x73, 0x5a, 0x8c, 0x5f, 0x12, 0xea, 0x1e, 0xd3, 0x80, 0x78, 0x3a, 0x88, 0x34, 0xc3, 0x2d,
	0x07, 0xa7, 0x96, 0x12, 0x5c, 0x5e, 0x82, 0x53, 0x32, 0x01, 0x4e, 0xe0, 0x77, 0x03, 0x6c, 0x07,
	0x16, 0x76, 0x1c, 0x4f, 0x2f, 0x84, 0xf8, 0x85, 0xac, 0xe6, 0x38, 0x1e, 0x4f, 0x1a, 0x1f, 0x12,
	0x7d, 0x59, 0x26, 0x8d, 0x0f, 0x09, 0xba, 0x01, 0x79, 0x5b, 0x14, 0xb0, 0x15, 0xd0, 0x01, 0xd1,
	0x8b, 0xc2, 0x06, 0xa4, 0xa8, 0x4b, 0x07, 0x42, 0x61, 0x34, 0x74, 0x22, 0x85, 0x8b, 0x52, 0x41,
	0x8a, 0xb8, 0x82, 0x41, 0xe1, 0xf2, 0xd4, 0x59, 0xfe, 0x87, 0x65, 0xf3, 0x53, 0x02, 0xae, 0xec,
	0x11, 0xcf, 0x3e, 0xc2, 0x6e, 0xe0, 0xef, 0xe1, 0x80, 0x78, 0x14, 0xf7, 0x17, 0xd4, 0xc6, 0x0d,
	0xc8, 0x0f, 0x94, 0x46, 0x58, 0x1c, 0x49, 0x13, 0x42, 0x51, 0xd3, 0x41, 0x5b, 0xb0, 0xec, 0x91,
	0x43, 0xea, 0x73, 0x4a, 0x05, 0x5f, 0xb2, 0x42, 0x0a, 0xa1, 0x50, 0x10, 0x76, 0x0b, 0x8a, 0x47,
	0x04, 0xf7, 0x83, 0xa3, 0xe8, 0xc8, 0x64, 0xcb, 0x29, 0x48, 0xa9, 0x3a, 0xb6, 0x32, 0x64, 0xa9,
	0x43, 0xdc, 0x80, 0x06, 0x63, 0x51, 0x35, 0x29, 0x33, 0xda, 0x4f, 0xca, 0x20, 0x1d, 0x2f, 0x83,
	0xeb, 0x90, 0x0f, 0xf0, 0x49, 0xe4, 0x54, 0x16, 0x4e, 0x2e, 0xc0, 0x27, 0xca, 0xe3, 0x2b, 0xc7,
	0x92, 0x7d, 0xdd, 0xb1, 0xe4, 0x66, 0x8e, 0xe5, 0x1b, 0x0d, 0xf4, 0x19, 0xae, 0xc2, 0x9b, 0x76,
	0x5f, 0xb1, 0x2d, 0x8f, 0x66, 0x43, 0xb1, 0x3d, 0x97, 0x5a, 0x49, 0x3d, 0x7a, 0x17, 0x8a, 0x6c,
	0x48, 0x3c, 0xf1, 0x02, 0xc8, 0x0e, 0x99, 0x10, 0x1d, 0x72, 0x45, 0xd9, 0xb6, 0xc3, 0x8f, 0xa2,
	0x47, 0x2e, 0xb3, 0xf8, 0xd6, 0x78, 0x0e, 0x6b, 0x73, 0xa0, 0x9c, 0xaf, 0x50, 0x5e, 0x77, 0xae,
	0xc6, 0x63, 0x58, 0x7f, 0x42, 0x82, 0x85, 0xa9, 0xbf, 0x62, 0xaf, 0xcd, 0xd8, 0x7f, 0x05, 0x1b,
	0xf3, 0xed, 0xcf, 0x87, 0xf7, 0xfe, 0x54, 0x61, 0xbf, 0x01, 0xd5, 0xc6, 0x17, 0x70, 0x2d, 0xfa,
	0x5c, 0xf3, 0x7d, 0x66, 0x53, 0x1c, 0x90, 0xce, 0x11, 0x1b, 0xbe, 0x69, 0x0a, 0x68, 0x15, 0x32,
	0xfe, 0x11, 0x1b, 0x4e, 0xf8, 0x49, 0xf3, 0x6d, 0xd3, 0x11, 0x5d, 0xc4, 0xb7, 0x70, 0xe8, 0x54,
	0x94, 0x7c, 0xd6, 0xcc, 0xd3, 0x49, 0x1c, 0xa3, 0x0d, 0xd7, 0x17, 0x45, 0x3f, 0x17, 0x01, 0xc6,
	0x67, 0xb1, 0x74, 0xc2, 0x6c, 0x6b, 0x23, 0x87, 0x06, 0x6f, 0x9c, 0xce, 0x3a, 0xe4, 0x30, 0x37,
	0xb0, 0x46, 0x51, 0x42, 0x59, 0x21, 0xe8, 0xc9, 0xb9, 0x82, 0x07, 0x22, 0x6e, 0xa0, 0x2e, 0x70,
	0xb8, 0x35, 0x7e, 0xd6, 0x62, 0xa9, 0xbc, 0x12, 0xf9, 0x7c, 0x67, 0x19, 0xdd, 0xe5, 0x44, 0xfc,
	0x2e, 0x2f, 0x44, 0xc0, 0xbb, 0x87, 0x4b, 0x4e, 0x02, 0x6b, 0x82, 0x7e, 0x49, 0xa0, 0x2f, 0x70,
	0x69, 0x2d, 0xcc, 0x60, 0x15, 0x32, 0xd4, 0xb7, 0xd8, 0x31, 0xf1, 0x44, 0xf3, 0xc8, 0x9a, 0x69,
	0xea, 0xb7, 0x8f, 0x89, 0x67, 0xbc, 0x0f, 0xc5, 0x69, 0x20, 0xc8, 0x80, 0xa5, 0xe8, 0x69, 0x2f,
	0x6e, 0x17, 0x15, 0x5a, 0x93, 0x88, 0xe9, 0xc0, 0x14, 0xdf, 0x78, 0x2b, 0x1c, 0xf8, 0x87, 0xea,
	0x35, 0xe4, 0xcb, 0xca, 0x8f, 0x1a, 0x64, 0x94, 0x0e, 0xca, 0x43, 0xa6, 0xd3, 0xab, 0xd7, 0x1b,
	0x9d, 0x4e, 0xe9, 0x02, 0x02, 0x48, 0x35, 0x4c, 0xb3, 0x6d, 0x96, 0xfe, 0x49, 0xa2, 0x15, 0x28,
	0xf6, 0x3a, 0x0d, 0xd3, 0x6a, 0xb5, 0xbb, 0x56, 0xe3, 0xe3, 0x66, 0xa7, 0x5b, 0xfa, 0xf5, 0x34,
	0x89, 0x4a, 0x00, 0x42, 0x2a, 0x25, 0xbf, 0x9d, 0x26, 0x91, 0x0e, 0x68, 0xaf, 0x61, 0xd6, 0x3f,
	0xa8, 0xb5, 0xba, 0x31, 0xdd, 0x97, 0xa7, 0xc2, 0x43, 0xf4, 0x45, 0x4a, 0x7f, 0x3f, 0x4d, 0xa2,
	0xcb, 0xb0, 0x5c, 0xab, 0xd7, 0xdb, 0xbd, 0x48, 0xf8, 0xc7, 0x69, 0x12, 0xad, 0xc2, 0xa5, 0x50,
	0x38, 0xf1, 0xf1, 0xe7, 0x69, 0xb2, 0xf2, 0x18, 0x96, 0xa7, 0x3a, 0x09, 0x02, 0x48, 0xd7, 0xcd,
	0x46, 0xad, 0xdb, 0x10, 0x70, 0xd3, 0xbd, 0xfd, 0x1d, 0xbe, 0xd6, 0xf8, 0x7a, 0xa7, 0xb1, 0xdb,
	0xe8, 0x36, 0x4a, 0x09, 0x94, 0x83, 0x54, 0xad, 0xb7, 0xd3, 0xec, 0x96, 0x92, 0x95, 0x0d, 0xc8,
	0x86, 0x33, 0x23, 0xca, 0x40, 0xb2, 0xde, 0x7a, 0x5a, 0xba, 0xc0, 0x17, 0xbd, 0xce, 0x4e, 0x49,
	0xab, 0x3c, 0x80, 0x42, 0x7c, 0x04, 0xe4, 0x4e, 0x5a, 0x6d, 0x73, 0xaf, 0xb6, 0x5b, 0xba, 0x80,
	0xb2, 0xb0, 0xb4, 0xdb, 0xae, 0x7f, 0x58, 0xd2, 0x38, 0x45, 0xcd, 0xd6, 0x47, 0xb5, 0xdd, 0xe6,
	0x4e, 0x29, 0x51, 0x79, 0x1b, 0xf2, 0xb1, 0xe1, 0x0f, 0x15, 0x20, 0xbb, 0xdf, 0x30, 0x3b, 0xed,
	0x96, 0xb0, 0xc9, 0x43, 0xa6, 0xde, 0xde, 0xdb, 0xaf, 0xb5, 0x9e, 0x4a, 0x44, 0x9d, 0xa7, 0x9d,
	0x6e, 0x63, 0xaf, 0x94, 0xd8, 0xfe, 0x2b, 0x01, 0x05, 0xfe, 0x76, 0xf9, 0x1d, 0xe2, 0x1d, 0x53,
	0x9b, 0xa0, 0x4f, 0x20, 0x1f, 0x7b, 0x24, 0xd1, 0x9a, 0x3a, 0xb9, 0xd9, 0x21, 0xa8, 0x5c, 0x9e,
	0xf7, 0x49, 0x1e, 0xbf, 0x71, 0xe5, 0xc5, 0xcb, 0xbf, 0xbf, 0x4b, 0x5c, 0x44, 0xcb, 0xd5, 0xe3,
	0x07, 0x62, 0xa4, 0xaf, 0x8a, 0xde, 0x3c, 0x9e, 0x9a, 0xa6, 0xd4, 0xfc, 0x86, 0x36, 0x67, 0x1d,
	0x4d, 0x0f, 0x8c, 0xe5, 0x9b, 0x67, 0x68, 0xa8, 0x88, 0xd7, 0x45, 0x44, 0x1d, 0x5d, 0x9d, 0x8a,
	0x58, 0x3d, 0x18, 0x5b, 0x72, 0xf4, 0xf9, 0x1c, 0x2e, 0xcd, 0xcc, 0xbf, 0xe8, 0x46, 0x78, 0x8b,
	0x16, 0xfc, 0x3b, 0x28, 0x6f, 0x2e, 0x56, 0x50, 0x71, 0x0d, 0x11, 0x77, 0xc3, 0x58, 0x8d, 0xe2,
	0xaa, 0xb1, 0xae, 0x2a, 0xdf, 0xc0, 0x47, 0x5a, 0x65, 0xfb, 0x97, 0x25, 0x28, 0x45, 0xf7, 0x3b,
	0x24, 0xfa, 0x4b, 0xb8, 0x34, 0x73, 0xe7, 0x23, 0x40, 0x8b, 0x1e, 0x85, 0x08, 0xd0, 0xc2, 0xae,
	0x6f, 0xdc, 0x16, 0x80, 0x36, 0x8d, 0xf5, 0x08, 0xd0, 0x20, 0xd4, 0xad, 0x86, 0xad, 0xea, 0x91,
	0x56, 0x41, 0xdf, 0x6a, 0x70, 0x75, 0x7e, 0xd3, 0x41, 0xb7, 0x16, 0x05, 0x89, 0x77, 0xc3, 0xf2,
	0xff, 0x5e, 0xa3, 0xa5, 0xf0, 0x6c, 0x09, 0x3c, 0xd7, 0xca, 0xfa, 0x1c, 0x3c, 0xa2, 0xdd, 0x70,
	0x30, 0x5f, 0x6b, 0xb0, 0x32, 0xef, 0x2d, 0x43, 0xc6, 0xe4, 0xe4, 0x17, 0x72, 0xb2, 0x75, 0xa6,
	0xce, 0x34, 0x0c, 0x74, 0x16, 0x2d, 0xe8, 0xfb, 0x38, 0x27, 0x53, 0x6f, 0xca, 0x2c, 0x27, 0xf3,
	0x1e, 0xbc, 0x59, 0x4e, 0xe6, 0x3e, 0x4c, 0xc6, 0x43, 0x01, 0xa6, 0x5a, 0xae, 0xcc, 0xe3, 0x24,
	0xb4, 0xa8, 0x8a, 0x97, 0xf1, 0x60, 0xe4, 0x53, 0x97, 0xf8, 0xfe, 0x23, 0xad, 0x72, 0x90, 0x16,
	0xff, 0x67, 0xdf, 0xfa, 0x37, 0x00, 0x00, 0xff, 0xff, 0xac, 0xca, 0x4b, 0xac, 0x48, 0x0f, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UsersServiceClient is the client API for UsersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersServiceClient interface {
	// 获取用户信息
	GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
	// 获取用户信息-手机号
	GetUserInfoByPhone(ctx context.Context, in *GetUserInfoByPhoneRequest, opts ...grpc.CallOption) (*GetUserInfoByPhoneResponse, error)
	// 创建用户账户
	CreateUserAccount(ctx context.Context, in *CreateUserAccountRequest, opts ...grpc.CallOption) (*CreateUserAccountResponse, error)
}

type usersServiceClient struct {
	cc *grpc.ClientConn
}

func NewUsersServiceClient(cc *grpc.ClientConn) UsersServiceClient {
	return &usersServiceClient{cc}
}

func (c *usersServiceClient) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	out := new(GetUserInfoResponse)
	err := c.cc.Invoke(ctx, "/users.UsersService/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) GetUserInfoByPhone(ctx context.Context, in *GetUserInfoByPhoneRequest, opts ...grpc.CallOption) (*GetUserInfoByPhoneResponse, error) {
	out := new(GetUserInfoByPhoneResponse)
	err := c.cc.Invoke(ctx, "/users.UsersService/GetUserInfoByPhone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) CreateUserAccount(ctx context.Context, in *CreateUserAccountRequest, opts ...grpc.CallOption) (*CreateUserAccountResponse, error) {
	out := new(CreateUserAccountResponse)
	err := c.cc.Invoke(ctx, "/users.UsersService/CreateUserAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServiceServer is the server API for UsersService service.
type UsersServiceServer interface {
	// 获取用户信息
	GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error)
	// 获取用户信息-手机号
	GetUserInfoByPhone(context.Context, *GetUserInfoByPhoneRequest) (*GetUserInfoByPhoneResponse, error)
	// 创建用户账户
	CreateUserAccount(context.Context, *CreateUserAccountRequest) (*CreateUserAccountResponse, error)
}

// UnimplementedUsersServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUsersServiceServer struct {
}

func (*UnimplementedUsersServiceServer) GetUserInfo(ctx context.Context, req *GetUserInfoRequest) (*GetUserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (*UnimplementedUsersServiceServer) GetUserInfoByPhone(ctx context.Context, req *GetUserInfoByPhoneRequest) (*GetUserInfoByPhoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfoByPhone not implemented")
}
func (*UnimplementedUsersServiceServer) CreateUserAccount(ctx context.Context, req *CreateUserAccountRequest) (*CreateUserAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserAccount not implemented")
}

func RegisterUsersServiceServer(s *grpc.Server, srv UsersServiceServer) {
	s.RegisterService(&_UsersService_serviceDesc, srv)
}

func _UsersService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UsersService/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetUserInfo(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_GetUserInfoByPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoByPhoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetUserInfoByPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UsersService/GetUserInfoByPhone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetUserInfoByPhone(ctx, req.(*GetUserInfoByPhoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_CreateUserAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).CreateUserAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UsersService/CreateUserAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).CreateUserAccount(ctx, req.(*CreateUserAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UsersService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "users.UsersService",
	HandlerType: (*UsersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _UsersService_GetUserInfo_Handler,
		},
		{
			MethodName: "GetUserInfoByPhone",
			Handler:    _UsersService_GetUserInfoByPhone_Handler,
		},
		{
			MethodName: "CreateUserAccount",
			Handler:    _UsersService_CreateUserAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/micro_mall_users_proto/users/users.proto",
}

// MerchantsServiceClient is the client API for MerchantsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MerchantsServiceClient interface {
	// 商户提交资料
	MerchantsMaterial(ctx context.Context, in *MerchantsMaterialRequest, opts ...grpc.CallOption) (*MerchantsMaterialResponse, error)
	// 审核商户,返回审核结果
	MerchantsMaterialAudit(ctx context.Context, in *MerchantsMaterialAuditRequest, opts ...grpc.CallOption) (*MerchantsMaterialAuditResponse, error)
	// 获取商户资料
	GetMerchantsMaterial(ctx context.Context, in *GetMerchantsMaterialRequest, opts ...grpc.CallOption) (*GetMerchantsMaterialResponse, error)
	// 商户关联店铺
	MerchantsAssociateShop(ctx context.Context, in *MerchantsAssociateShopRequest, opts ...grpc.CallOption) (*MerchantsAssociateShopResponse, error)
}

type merchantsServiceClient struct {
	cc *grpc.ClientConn
}

func NewMerchantsServiceClient(cc *grpc.ClientConn) MerchantsServiceClient {
	return &merchantsServiceClient{cc}
}

func (c *merchantsServiceClient) MerchantsMaterial(ctx context.Context, in *MerchantsMaterialRequest, opts ...grpc.CallOption) (*MerchantsMaterialResponse, error) {
	out := new(MerchantsMaterialResponse)
	err := c.cc.Invoke(ctx, "/users.MerchantsService/MerchantsMaterial", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantsServiceClient) MerchantsMaterialAudit(ctx context.Context, in *MerchantsMaterialAuditRequest, opts ...grpc.CallOption) (*MerchantsMaterialAuditResponse, error) {
	out := new(MerchantsMaterialAuditResponse)
	err := c.cc.Invoke(ctx, "/users.MerchantsService/MerchantsMaterialAudit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantsServiceClient) GetMerchantsMaterial(ctx context.Context, in *GetMerchantsMaterialRequest, opts ...grpc.CallOption) (*GetMerchantsMaterialResponse, error) {
	out := new(GetMerchantsMaterialResponse)
	err := c.cc.Invoke(ctx, "/users.MerchantsService/GetMerchantsMaterial", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantsServiceClient) MerchantsAssociateShop(ctx context.Context, in *MerchantsAssociateShopRequest, opts ...grpc.CallOption) (*MerchantsAssociateShopResponse, error) {
	out := new(MerchantsAssociateShopResponse)
	err := c.cc.Invoke(ctx, "/users.MerchantsService/MerchantsAssociateShop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MerchantsServiceServer is the server API for MerchantsService service.
type MerchantsServiceServer interface {
	// 商户提交资料
	MerchantsMaterial(context.Context, *MerchantsMaterialRequest) (*MerchantsMaterialResponse, error)
	// 审核商户,返回审核结果
	MerchantsMaterialAudit(context.Context, *MerchantsMaterialAuditRequest) (*MerchantsMaterialAuditResponse, error)
	// 获取商户资料
	GetMerchantsMaterial(context.Context, *GetMerchantsMaterialRequest) (*GetMerchantsMaterialResponse, error)
	// 商户关联店铺
	MerchantsAssociateShop(context.Context, *MerchantsAssociateShopRequest) (*MerchantsAssociateShopResponse, error)
}

// UnimplementedMerchantsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMerchantsServiceServer struct {
}

func (*UnimplementedMerchantsServiceServer) MerchantsMaterial(ctx context.Context, req *MerchantsMaterialRequest) (*MerchantsMaterialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MerchantsMaterial not implemented")
}
func (*UnimplementedMerchantsServiceServer) MerchantsMaterialAudit(ctx context.Context, req *MerchantsMaterialAuditRequest) (*MerchantsMaterialAuditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MerchantsMaterialAudit not implemented")
}
func (*UnimplementedMerchantsServiceServer) GetMerchantsMaterial(ctx context.Context, req *GetMerchantsMaterialRequest) (*GetMerchantsMaterialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMerchantsMaterial not implemented")
}
func (*UnimplementedMerchantsServiceServer) MerchantsAssociateShop(ctx context.Context, req *MerchantsAssociateShopRequest) (*MerchantsAssociateShopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MerchantsAssociateShop not implemented")
}

func RegisterMerchantsServiceServer(s *grpc.Server, srv MerchantsServiceServer) {
	s.RegisterService(&_MerchantsService_serviceDesc, srv)
}

func _MerchantsService_MerchantsMaterial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantsMaterialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantsServiceServer).MerchantsMaterial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.MerchantsService/MerchantsMaterial",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantsServiceServer).MerchantsMaterial(ctx, req.(*MerchantsMaterialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantsService_MerchantsMaterialAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantsMaterialAuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantsServiceServer).MerchantsMaterialAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.MerchantsService/MerchantsMaterialAudit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantsServiceServer).MerchantsMaterialAudit(ctx, req.(*MerchantsMaterialAuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantsService_GetMerchantsMaterial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMerchantsMaterialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantsServiceServer).GetMerchantsMaterial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.MerchantsService/GetMerchantsMaterial",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantsServiceServer).GetMerchantsMaterial(ctx, req.(*GetMerchantsMaterialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantsService_MerchantsAssociateShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantsAssociateShopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantsServiceServer).MerchantsAssociateShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.MerchantsService/MerchantsAssociateShop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantsServiceServer).MerchantsAssociateShop(ctx, req.(*MerchantsAssociateShopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MerchantsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "users.MerchantsService",
	HandlerType: (*MerchantsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MerchantsMaterial",
			Handler:    _MerchantsService_MerchantsMaterial_Handler,
		},
		{
			MethodName: "MerchantsMaterialAudit",
			Handler:    _MerchantsService_MerchantsMaterialAudit_Handler,
		},
		{
			MethodName: "GetMerchantsMaterial",
			Handler:    _MerchantsService_GetMerchantsMaterial_Handler,
		},
		{
			MethodName: "MerchantsAssociateShop",
			Handler:    _MerchantsService_MerchantsAssociateShop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/micro_mall_users_proto/users/users.proto",
}
